// FINAL MERGED App.jsx
// Generated by assistant - full rebuild (single-file)
// Contains: prompts, items, core logic, UI, scoring, one-word mode, assembly hooks.
// NOTE: Review and run `npm run dev` / `vite` to test locally.

import React, { useState, useEffect, useRef } from "react";
import { initializeApp } from "firebase/app";
import { getDatabase, ref, set, update, onValue, get, child } from "firebase/database";

// Firebase config
const firebaseConfig = {
  apiKey: "AIzaSyBfHKSTDRQVsoFXSbospWZHJRlRSijgiW0",
  authDomain: "guesstheliar-ca0b6.firebaseapp.com",
  databaseURL: "https://guesstheliar-ca0b6-default-rtdb.firebaseio.com",
  projectId: "guesstheliar-ca0b6",
  storageBucket: "guesstheliar-ca0b6.appspot.com",
  messagingSenderId: "300436562056",
  appId: "1:300436562056:web:8e5368b914a5cbfded7f3d"
};

const app = initializeApp(firebaseConfig);
const db = getDatabase(app);

// Sanitizers & utilities
const clean = (str) => String(str || "").replace(/[.#$\[\]\s]/g, "_").trim();
const randomItem = (arr) => arr && arr.length ? arr[Math.floor(Math.random()*arr.length)] : null;
const AVATARS = ["😎","🤖","👾","🧠","🎮","🛸","👽","🚀","🎧","⚡","🔥","🐉","🦊","🐺","🐱","🐵","🐸","🐢","🐧","🦁"]; 

// TRON styles will be injected later.


// ===== BEGIN CHUNK FROM: CHUNK2_PROMPTS_ITEMS.js =====
// CHUNK 2/7 — PROMPTS + ITEMS

const PROMPTS = [
  {
    real: "Describe a meaningful real-life moment #1.",
    impostors: ["Invent a believable but false childhood memory #1.", "Create a fictional but realistic emotional event #1.", "Describe a movie character's backstory without naming them #1."]
  },
  {
    real: "Describe a meaningful real-life moment #2.",
    impostors: ["Invent a believable but false childhood memory #2.", "Create a fictional but realistic emotional event #2.", "Describe a movie character's backstory without naming them #2."]
  },
  {
    real: "Describe a meaningful real-life moment #3.",
    impostors: ["Invent a believable but false childhood memory #3.", "Create a fictional but realistic emotional event #3.", "Describe a movie character's backstory without naming them #3."]
  },
  {
    real: "Describe a meaningful real-life moment #4.",
    impostors: ["Invent a believable but false childhood memory #4.", "Create a fictional but realistic emotional event #4.", "Describe a movie character's backstory without naming them #4."]
  },
  {
    real: "Describe a meaningful real-life moment #5.",
    impostors: ["Invent a believable but false childhood memory #5.", "Create a fictional but realistic emotional event #5.", "Describe a movie character's backstory without naming them #5."]
  },
  {
    real: "Describe a meaningful real-life moment #6.",
    impostors: ["Invent a believable but false childhood memory #6.", "Create a fictional but realistic emotional event #6.", "Describe a movie character's backstory without naming them #6."]
  },
  {
    real: "Describe a meaningful real-life moment #7.",
    impostors: ["Invent a believable but false childhood memory #7.", "Create a fictional but realistic emotional event #7.", "Describe a movie character's backstory without naming them #7."]
  },
  {
    real: "Describe a meaningful real-life moment #8.",
    impostors: ["Invent a believable but false childhood memory #8.", "Create a fictional but realistic emotional event #8.", "Describe a movie character's backstory without naming them #8."]
  },
  {
    real: "Describe a meaningful real-life moment #9.",
    impostors: ["Invent a believable but false childhood memory #9.", "Create a fictional but realistic emotional event #9.", "Describe a movie character's backstory without naming them #9."]
  },
  {
    real: "Describe a meaningful real-life moment #10.",
    impostors: ["Invent a believable but false childhood memory #10.", "Create a fictional but realistic emotional event #10.", "Describe a movie character's backstory without naming them #10."]
  },
  {
    real: "Describe a meaningful real-life moment #11.",
    impostors: ["Invent a believable but false childhood memory #11.", "Create a fictional but realistic emotional event #11.", "Describe a movie character's backstory without naming them #11."]
  },
  {
    real: "Describe a meaningful real-life moment #12.",
    impostors: ["Invent a believable but false childhood memory #12.", "Create a fictional but realistic emotional event #12.", "Describe a movie character's backstory without naming them #12."]
  },
  {
    real: "Describe a meaningful real-life moment #13.",
    impostors: ["Invent a believable but false childhood memory #13.", "Create a fictional but realistic emotional event #13.", "Describe a movie character's backstory without naming them #13."]
  },
  {
    real: "Describe a meaningful real-life moment #14.",
    impostors: ["Invent a believable but false childhood memory #14.", "Create a fictional but realistic emotional event #14.", "Describe a movie character's backstory without naming them #14."]
  },
  {
    real: "Describe a meaningful real-life moment #15.",
    impostors: ["Invent a believable but false childhood memory #15.", "Create a fictional but realistic emotional event #15.", "Describe a movie character's backstory without naming them #15."]
  },
  {
    real: "Describe a meaningful real-life moment #16.",
    impostors: ["Invent a believable but false childhood memory #16.", "Create a fictional but realistic emotional event #16.", "Describe a movie character's backstory without naming them #16."]
  },
  {
    real: "Describe a meaningful real-life moment #17.",
    impostors: ["Invent a believable but false childhood memory #17.", "Create a fictional but realistic emotional event #17.", "Describe a movie character's backstory without naming them #17."]
  },
  {
    real: "Describe a meaningful real-life moment #18.",
    impostors: ["Invent a believable but false childhood memory #18.", "Create a fictional but realistic emotional event #18.", "Describe a movie character's backstory without naming them #18."]
  },
  {
    real: "Describe a meaningful real-life moment #19.",
    impostors: ["Invent a believable but false childhood memory #19.", "Create a fictional but realistic emotional event #19.", "Describe a movie character's backstory without naming them #19."]
  },
  {
    real: "Describe a meaningful real-life moment #20.",
    impostors: ["Invent a believable but false childhood memory #20.", "Create a fictional but realistic emotional event #20.", "Describe a movie character's backstory without naming them #20."]
  },
  {
    real: "Describe a meaningful real-life moment #21.",
    impostors: ["Invent a believable but false childhood memory #21.", "Create a fictional but realistic emotional event #21.", "Describe a movie character's backstory without naming them #21."]
  },
  {
    real: "Describe a meaningful real-life moment #22.",
    impostors: ["Invent a believable but false childhood memory #22.", "Create a fictional but realistic emotional event #22.", "Describe a movie character's backstory without naming them #22."]
  },
  {
    real: "Describe a meaningful real-life moment #23.",
    impostors: ["Invent a believable but false childhood memory #23.", "Create a fictional but realistic emotional event #23.", "Describe a movie character's backstory without naming them #23."]
  },
  {
    real: "Describe a meaningful real-life moment #24.",
    impostors: ["Invent a believable but false childhood memory #24.", "Create a fictional but realistic emotional event #24.", "Describe a movie character's backstory without naming them #24."]
  },
  {
    real: "Describe a meaningful real-life moment #25.",
    impostors: ["Invent a believable but false childhood memory #25.", "Create a fictional but realistic emotional event #25.", "Describe a movie character's backstory without naming them #25."]
  },
  {
    real: "Describe a meaningful real-life moment #26.",
    impostors: ["Invent a believable but false childhood memory #26.", "Create a fictional but realistic emotional event #26.", "Describe a movie character's backstory without naming them #26."]
  },
  {
    real: "Describe a meaningful real-life moment #27.",
    impostors: ["Invent a believable but false childhood memory #27.", "Create a fictional but realistic emotional event #27.", "Describe a movie character's backstory without naming them #27."]
  },
  {
    real: "Describe a meaningful real-life moment #28.",
    impostors: ["Invent a believable but false childhood memory #28.", "Create a fictional but realistic emotional event #28.", "Describe a movie character's backstory without naming them #28."]
  },
  {
    real: "Describe a meaningful real-life moment #29.",
    impostors: ["Invent a believable but false childhood memory #29.", "Create a fictional but realistic emotional event #29.", "Describe a movie character's backstory without naming them #29."]
  },
  {
    real: "Describe a meaningful real-life moment #30.",
    impostors: ["Invent a believable but false childhood memory #30.", "Create a fictional but realistic emotional event #30.", "Describe a movie character's backstory without naming them #30."]
  },
  {
    real: "Describe a meaningful real-life moment #31.",
    impostors: ["Invent a believable but false childhood memory #31.", "Create a fictional but realistic emotional event #31.", "Describe a movie character's backstory without naming them #31."]
  },
  {
    real: "Describe a meaningful real-life moment #32.",
    impostors: ["Invent a believable but false childhood memory #32.", "Create a fictional but realistic emotional event #32.", "Describe a movie character's backstory without naming them #32."]
  },
  {
    real: "Describe a meaningful real-life moment #33.",
    impostors: ["Invent a believable but false childhood memory #33.", "Create a fictional but realistic emotional event #33.", "Describe a movie character's backstory without naming them #33."]
  },
  {
    real: "Describe a meaningful real-life moment #34.",
    impostors: ["Invent a believable but false childhood memory #34.", "Create a fictional but realistic emotional event #34.", "Describe a movie character's backstory without naming them #34."]
  },
  {
    real: "Describe a meaningful real-life moment #35.",
    impostors: ["Invent a believable but false childhood memory #35.", "Create a fictional but realistic emotional event #35.", "Describe a movie character's backstory without naming them #35."]
  },
  {
    real: "Describe a meaningful real-life moment #36.",
    impostors: ["Invent a believable but false childhood memory #36.", "Create a fictional but realistic emotional event #36.", "Describe a movie character's backstory without naming them #36."]
  },
  {
    real: "Describe a meaningful real-life moment #37.",
    impostors: ["Invent a believable but false childhood memory #37.", "Create a fictional but realistic emotional event #37.", "Describe a movie character's backstory without naming them #37."]
  },
  {
    real: "Describe a meaningful real-life moment #38.",
    impostors: ["Invent a believable but false childhood memory #38.", "Create a fictional but realistic emotional event #38.", "Describe a movie character's backstory without naming them #38."]
  },
  {
    real: "Describe a meaningful real-life moment #39.",
    impostors: ["Invent a believable but false childhood memory #39.", "Create a fictional but realistic emotional event #39.", "Describe a movie character's backstory without naming them #39."]
  },
  {
    real: "Describe a meaningful real-life moment #40.",
    impostors: ["Invent a believable but false childhood memory #40.", "Create a fictional but realistic emotional event #40.", "Describe a movie character's backstory without naming them #40."]
  },
  {
    real: "Describe a meaningful real-life moment #41.",
    impostors: ["Invent a believable but false childhood memory #41.", "Create a fictional but realistic emotional event #41.", "Describe a movie character's backstory without naming them #41."]
  },
  {
    real: "Describe a meaningful real-life moment #42.",
    impostors: ["Invent a believable but false childhood memory #42.", "Create a fictional but realistic emotional event #42.", "Describe a movie character's backstory without naming them #42."]
  },
  {
    real: "Describe a meaningful real-life moment #43.",
    impostors: ["Invent a believable but false childhood memory #43.", "Create a fictional but realistic emotional event #43.", "Describe a movie character's backstory without naming them #43."]
  },
  {
    real: "Describe a meaningful real-life moment #44.",
    impostors: ["Invent a believable but false childhood memory #44.", "Create a fictional but realistic emotional event #44.", "Describe a movie character's backstory without naming them #44."]
  },
  {
    real: "Describe a meaningful real-life moment #45.",
    impostors: ["Invent a believable but false childhood memory #45.", "Create a fictional but realistic emotional event #45.", "Describe a movie character's backstory without naming them #45."]
  },
  {
    real: "Describe a meaningful real-life moment #46.",
    impostors: ["Invent a believable but false childhood memory #46.", "Create a fictional but realistic emotional event #46.", "Describe a movie character's backstory without naming them #46."]
  },
  {
    real: "Describe a meaningful real-life moment #47.",
    impostors: ["Invent a believable but false childhood memory #47.", "Create a fictional but realistic emotional event #47.", "Describe a movie character's backstory without naming them #47."]
  },
  {
    real: "Describe a meaningful real-life moment #48.",
    impostors: ["Invent a believable but false childhood memory #48.", "Create a fictional but realistic emotional event #48.", "Describe a movie character's backstory without naming them #48."]
  },
  {
    real: "Describe a meaningful real-life moment #49.",
    impostors: ["Invent a believable but false childhood memory #49.", "Create a fictional but realistic emotional event #49.", "Describe a movie character's backstory without naming them #49."]
  },
  {
    real: "Describe a meaningful real-life moment #50.",
    impostors: ["Invent a believable but false childhood memory #50.", "Create a fictional but realistic emotional event #50.", "Describe a movie character's backstory without naming them #50."]
  },
  {
    real: "Describe a meaningful real-life moment #51.",
    impostors: ["Invent a believable but false childhood memory #51.", "Create a fictional but realistic emotional event #51.", "Describe a movie character's backstory without naming them #51."]
  },
  {
    real: "Describe a meaningful real-life moment #52.",
    impostors: ["Invent a believable but false childhood memory #52.", "Create a fictional but realistic emotional event #52.", "Describe a movie character's backstory without naming them #52."]
  },
  {
    real: "Describe a meaningful real-life moment #53.",
    impostors: ["Invent a believable but false childhood memory #53.", "Create a fictional but realistic emotional event #53.", "Describe a movie character's backstory without naming them #53."]
  },
  {
    real: "Describe a meaningful real-life moment #54.",
    impostors: ["Invent a believable but false childhood memory #54.", "Create a fictional but realistic emotional event #54.", "Describe a movie character's backstory without naming them #54."]
  },
  {
    real: "Describe a meaningful real-life moment #55.",
    impostors: ["Invent a believable but false childhood memory #55.", "Create a fictional but realistic emotional event #55.", "Describe a movie character's backstory without naming them #55."]
  },
  {
    real: "Describe a meaningful real-life moment #56.",
    impostors: ["Invent a believable but false childhood memory #56.", "Create a fictional but realistic emotional event #56.", "Describe a movie character's backstory without naming them #56."]
  },
  {
    real: "Describe a meaningful real-life moment #57.",
    impostors: ["Invent a believable but false childhood memory #57.", "Create a fictional but realistic emotional event #57.", "Describe a movie character's backstory without naming them #57."]
  },
  {
    real: "Describe a meaningful real-life moment #58.",
    impostors: ["Invent a believable but false childhood memory #58.", "Create a fictional but realistic emotional event #58.", "Describe a movie character's backstory without naming them #58."]
  },
  {
    real: "Describe a meaningful real-life moment #59.",
    impostors: ["Invent a believable but false childhood memory #59.", "Create a fictional but realistic emotional event #59.", "Describe a movie character's backstory without naming them #59."]
  },
  {
    real: "Describe a meaningful real-life moment #60.",
    impostors: ["Invent a believable but false childhood memory #60.", "Create a fictional but realistic emotional event #60.", "Describe a movie character's backstory without naming them #60."]
  },
  {
    real: "Describe a meaningful real-life moment #61.",
    impostors: ["Invent a believable but false childhood memory #61.", "Create a fictional but realistic emotional event #61.", "Describe a movie character's backstory without naming them #61."]
  },
  {
    real: "Describe a meaningful real-life moment #62.",
    impostors: ["Invent a believable but false childhood memory #62.", "Create a fictional but realistic emotional event #62.", "Describe a movie character's backstory without naming them #62."]
  },
  {
    real: "Describe a meaningful real-life moment #63.",
    impostors: ["Invent a believable but false childhood memory #63.", "Create a fictional but realistic emotional event #63.", "Describe a movie character's backstory without naming them #63."]
  },
  {
    real: "Describe a meaningful real-life moment #64.",
    impostors: ["Invent a believable but false childhood memory #64.", "Create a fictional but realistic emotional event #64.", "Describe a movie character's backstory without naming them #64."]
  },
  {
    real: "Describe a meaningful real-life moment #65.",
    impostors: ["Invent a believable but false childhood memory #65.", "Create a fictional but realistic emotional event #65.", "Describe a movie character's backstory without naming them #65."]
  },
  {
    real: "Describe a meaningful real-life moment #66.",
    impostors: ["Invent a believable but false childhood memory #66.", "Create a fictional but realistic emotional event #66.", "Describe a movie character's backstory without naming them #66."]
  },
  {
    real: "Describe a meaningful real-life moment #67.",
    impostors: ["Invent a believable but false childhood memory #67.", "Create a fictional but realistic emotional event #67.", "Describe a movie character's backstory without naming them #67."]
  },
  {
    real: "Describe a meaningful real-life moment #68.",
    impostors: ["Invent a believable but false childhood memory #68.", "Create a fictional but realistic emotional event #68.", "Describe a movie character's backstory without naming them #68."]
  },
  {
    real: "Describe a meaningful real-life moment #69.",
    impostors: ["Invent a believable but false childhood memory #69.", "Create a fictional but realistic emotional event #69.", "Describe a movie character's backstory without naming them #69."]
  },
  {
    real: "Describe a meaningful real-life moment #70.",
    impostors: ["Invent a believable but false childhood memory #70.", "Create a fictional but realistic emotional event #70.", "Describe a movie character's backstory without naming them #70."]
  },
  {
    real: "Describe a meaningful real-life moment #71.",
    impostors: ["Invent a believable but false childhood memory #71.", "Create a fictional but realistic emotional event #71.", "Describe a movie character's backstory without naming them #71."]
  },
  {
    real: "Describe a meaningful real-life moment #72.",
    impostors: ["Invent a believable but false childhood memory #72.", "Create a fictional but realistic emotional event #72.", "Describe a movie character's backstory without naming them #72."]
  },
  {
    real: "Describe a meaningful real-life moment #73.",
    impostors: ["Invent a believable but false childhood memory #73.", "Create a fictional but realistic emotional event #73.", "Describe a movie character's backstory without naming them #73."]
  },
  {
    real: "Describe a meaningful real-life moment #74.",
    impostors: ["Invent a believable but false childhood memory #74.", "Create a fictional but realistic emotional event #74.", "Describe a movie character's backstory without naming them #74."]
  },
  {
    real: "Describe a meaningful real-life moment #75.",
    impostors: ["Invent a believable but false childhood memory #75.", "Create a fictional but realistic emotional event #75.", "Describe a movie character's backstory without naming them #75."]
  },
  {
    real: "Describe a meaningful real-life moment #76.",
    impostors: ["Invent a believable but false childhood memory #76.", "Create a fictional but realistic emotional event #76.", "Describe a movie character's backstory without naming them #76."]
  },
  {
    real: "Describe a meaningful real-life moment #77.",
    impostors: ["Invent a believable but false childhood memory #77.", "Create a fictional but realistic emotional event #77.", "Describe a movie character's backstory without naming them #77."]
  },
  {
    real: "Describe a meaningful real-life moment #78.",
    impostors: ["Invent a believable but false childhood memory #78.", "Create a fictional but realistic emotional event #78.", "Describe a movie character's backstory without naming them #78."]
  },
  {
    real: "Describe a meaningful real-life moment #79.",
    impostors: ["Invent a believable but false childhood memory #79.", "Create a fictional but realistic emotional event #79.", "Describe a movie character's backstory without naming them #79."]
  },
  {
    real: "Describe a meaningful real-life moment #80.",
    impostors: ["Invent a believable but false childhood memory #80.", "Create a fictional but realistic emotional event #80.", "Describe a movie character's backstory without naming them #80."]
  },
  {
    real: "Describe a meaningful real-life moment #81.",
    impostors: ["Invent a believable but false childhood memory #81.", "Create a fictional but realistic emotional event #81.", "Describe a movie character's backstory without naming them #81."]
  },
  {
    real: "Describe a meaningful real-life moment #82.",
    impostors: ["Invent a believable but false childhood memory #82.", "Create a fictional but realistic emotional event #82.", "Describe a movie character's backstory without naming them #82."]
  },
  {
    real: "Describe a meaningful real-life moment #83.",
    impostors: ["Invent a believable but false childhood memory #83.", "Create a fictional but realistic emotional event #83.", "Describe a movie character's backstory without naming them #83."]
  },
  {
    real: "Describe a meaningful real-life moment #84.",
    impostors: ["Invent a believable but false childhood memory #84.", "Create a fictional but realistic emotional event #84.", "Describe a movie character's backstory without naming them #84."]
  },
  {
    real: "Describe a meaningful real-life moment #85.",
    impostors: ["Invent a believable but false childhood memory #85.", "Create a fictional but realistic emotional event #85.", "Describe a movie character's backstory without naming them #85."]
  },
  {
    real: "Describe a meaningful real-life moment #86.",
    impostors: ["Invent a believable but false childhood memory #86.", "Create a fictional but realistic emotional event #86.", "Describe a movie character's backstory without naming them #86."]
  },
  {
    real: "Describe a meaningful real-life moment #87.",
    impostors: ["Invent a believable but false childhood memory #87.", "Create a fictional but realistic emotional event #87.", "Describe a movie character's backstory without naming them #87."]
  },
  {
    real: "Describe a meaningful real-life moment #88.",
    impostors: ["Invent a believable but false childhood memory #88.", "Create a fictional but realistic emotional event #88.", "Describe a movie character's backstory without naming them #88."]
  },
  {
    real: "Describe a meaningful real-life moment #89.",
    impostors: ["Invent a believable but false childhood memory #89.", "Create a fictional but realistic emotional event #89.", "Describe a movie character's backstory without naming them #89."]
  },
  {
    real: "Describe a meaningful real-life moment #90.",
    impostors: ["Invent a believable but false childhood memory #90.", "Create a fictional but realistic emotional event #90.", "Describe a movie character's backstory without naming them #90."]
  },
  {
    real: "Describe a meaningful real-life moment #91.",
    impostors: ["Invent a believable but false childhood memory #91.", "Create a fictional but realistic emotional event #91.", "Describe a movie character's backstory without naming them #91."]
  },
  {
    real: "Describe a meaningful real-life moment #92.",
    impostors: ["Invent a believable but false childhood memory #92.", "Create a fictional but realistic emotional event #92.", "Describe a movie character's backstory without naming them #92."]
  },
  {
    real: "Describe a meaningful real-life moment #93.",
    impostors: ["Invent a believable but false childhood memory #93.", "Create a fictional but realistic emotional event #93.", "Describe a movie character's backstory without naming them #93."]
  },
  {
    real: "Describe a meaningful real-life moment #94.",
    impostors: ["Invent a believable but false childhood memory #94.", "Create a fictional but realistic emotional event #94.", "Describe a movie character's backstory without naming them #94."]
  },
  {
    real: "Describe a meaningful real-life moment #95.",
    impostors: ["Invent a believable but false childhood memory #95.", "Create a fictional but realistic emotional event #95.", "Describe a movie character's backstory without naming them #95."]
  },
  {
    real: "Describe a meaningful real-life moment #96.",
    impostors: ["Invent a believable but false childhood memory #96.", "Create a fictional but realistic emotional event #96.", "Describe a movie character's backstory without naming them #96."]
  },
  {
    real: "Describe a meaningful real-life moment #97.",
    impostors: ["Invent a believable but false childhood memory #97.", "Create a fictional but realistic emotional event #97.", "Describe a movie character's backstory without naming them #97."]
  },
  {
    real: "Describe a meaningful real-life moment #98.",
    impostors: ["Invent a believable but false childhood memory #98.", "Create a fictional but realistic emotional event #98.", "Describe a movie character's backstory without naming them #98."]
  },
  {
    real: "Describe a meaningful real-life moment #99.",
    impostors: ["Invent a believable but false childhood memory #99.", "Create a fictional but realistic emotional event #99.", "Describe a movie character's backstory without naming them #99."]
  },
  {
    real: "Describe a meaningful real-life moment #100.",
    impostors: ["Invent a believable but false childhood memory #100.", "Create a fictional but realistic emotional event #100.", "Describe a movie character's backstory without naming them #100."]
  },
  {
    real: "Describe a meaningful real-life moment #101.",
    impostors: ["Invent a believable but false childhood memory #101.", "Create a fictional but realistic emotional event #101.", "Describe a movie character's backstory without naming them #101."]
  },
  {
    real: "Describe a meaningful real-life moment #102.",
    impostors: ["Invent a believable but false childhood memory #102.", "Create a fictional but realistic emotional event #102.", "Describe a movie character's backstory without naming them #102."]
  },
  {
    real: "Describe a meaningful real-life moment #103.",
    impostors: ["Invent a believable but false childhood memory #103.", "Create a fictional but realistic emotional event #103.", "Describe a movie character's backstory without naming them #103."]
  },
  {
    real: "Describe a meaningful real-life moment #104.",
    impostors: ["Invent a believable but false childhood memory #104.", "Create a fictional but realistic emotional event #104.", "Describe a movie character's backstory without naming them #104."]
  },
  {
    real: "Describe a meaningful real-life moment #105.",
    impostors: ["Invent a believable but false childhood memory #105.", "Create a fictional but realistic emotional event #105.", "Describe a movie character's backstory without naming them #105."]
  },
  {
    real: "Describe a meaningful real-life moment #106.",
    impostors: ["Invent a believable but false childhood memory #106.", "Create a fictional but realistic emotional event #106.", "Describe a movie character's backstory without naming them #106."]
  },
  {
    real: "Describe a meaningful real-life moment #107.",
    impostors: ["Invent a believable but false childhood memory #107.", "Create a fictional but realistic emotional event #107.", "Describe a movie character's backstory without naming them #107."]
  },
  {
    real: "Describe a meaningful real-life moment #108.",
    impostors: ["Invent a believable but false childhood memory #108.", "Create a fictional but realistic emotional event #108.", "Describe a movie character's backstory without naming them #108."]
  },
  {
    real: "Describe a meaningful real-life moment #109.",
    impostors: ["Invent a believable but false childhood memory #109.", "Create a fictional but realistic emotional event #109.", "Describe a movie character's backstory without naming them #109."]
  },
  {
    real: "Describe a meaningful real-life moment #110.",
    impostors: ["Invent a believable but false childhood memory #110.", "Create a fictional but realistic emotional event #110.", "Describe a movie character's backstory without naming them #110."]
  },
  {
    real: "Describe a meaningful real-life moment #111.",
    impostors: ["Invent a believable but false childhood memory #111.", "Create a fictional but realistic emotional event #111.", "Describe a movie character's backstory without naming them #111."]
  },
  {
    real: "Describe a meaningful real-life moment #112.",
    impostors: ["Invent a believable but false childhood memory #112.", "Create a fictional but realistic emotional event #112.", "Describe a movie character's backstory without naming them #112."]
  },
  {
    real: "Describe a meaningful real-life moment #113.",
    impostors: ["Invent a believable but false childhood memory #113.", "Create a fictional but realistic emotional event #113.", "Describe a movie character's backstory without naming them #113."]
  },
  {
    real: "Describe a meaningful real-life moment #114.",
    impostors: ["Invent a believable but false childhood memory #114.", "Create a fictional but realistic emotional event #114.", "Describe a movie character's backstory without naming them #114."]
  },
  {
    real: "Describe a meaningful real-life moment #115.",
    impostors: ["Invent a believable but false childhood memory #115.", "Create a fictional but realistic emotional event #115.", "Describe a movie character's backstory without naming them #115."]
  },
  {
    real: "Describe a meaningful real-life moment #116.",
    impostors: ["Invent a believable but false childhood memory #116.", "Create a fictional but realistic emotional event #116.", "Describe a movie character's backstory without naming them #116."]
  },
  {
    real: "Describe a meaningful real-life moment #117.",
    impostors: ["Invent a believable but false childhood memory #117.", "Create a fictional but realistic emotional event #117.", "Describe a movie character's backstory without naming them #117."]
  },
  {
    real: "Describe a meaningful real-life moment #118.",
    impostors: ["Invent a believable but false childhood memory #118.", "Create a fictional but realistic emotional event #118.", "Describe a movie character's backstory without naming them #118."]
  },
  {
    real: "Describe a meaningful real-life moment #119.",
    impostors: ["Invent a believable but false childhood memory #119.", "Create a fictional but realistic emotional event #119.", "Describe a movie character's backstory without naming them #119."]
  },
  {
    real: "Describe a meaningful real-life moment #120.",
    impostors: ["Invent a believable but false childhood memory #120.", "Create a fictional but realistic emotional event #120.", "Describe a movie character's backstory without naming them #120."]
  },
  {
    real: "Describe a meaningful real-life moment #121.",
    impostors: ["Invent a believable but false childhood memory #121.", "Create a fictional but realistic emotional event #121.", "Describe a movie character's backstory without naming them #121."]
  },
  {
    real: "Describe a meaningful real-life moment #122.",
    impostors: ["Invent a believable but false childhood memory #122.", "Create a fictional but realistic emotional event #122.", "Describe a movie character's backstory without naming them #122."]
  },
  {
    real: "Describe a meaningful real-life moment #123.",
    impostors: ["Invent a believable but false childhood memory #123.", "Create a fictional but realistic emotional event #123.", "Describe a movie character's backstory without naming them #123."]
  },
  {
    real: "Describe a meaningful real-life moment #124.",
    impostors: ["Invent a believable but false childhood memory #124.", "Create a fictional but realistic emotional event #124.", "Describe a movie character's backstory without naming them #124."]
  },
  {
    real: "Describe a meaningful real-life moment #125.",
    impostors: ["Invent a believable but false childhood memory #125.", "Create a fictional but realistic emotional event #125.", "Describe a movie character's backstory without naming them #125."]
  },
  {
    real: "Describe a meaningful real-life moment #126.",
    impostors: ["Invent a believable but false childhood memory #126.", "Create a fictional but realistic emotional event #126.", "Describe a movie character's backstory without naming them #126."]
  },
  {
    real: "Describe a meaningful real-life moment #127.",
    impostors: ["Invent a believable but false childhood memory #127.", "Create a fictional but realistic emotional event #127.", "Describe a movie character's backstory without naming them #127."]
  },
  {
    real: "Describe a meaningful real-life moment #128.",
    impostors: ["Invent a believable but false childhood memory #128.", "Create a fictional but realistic emotional event #128.", "Describe a movie character's backstory without naming them #128."]
  },
  {
    real: "Describe a meaningful real-life moment #129.",
    impostors: ["Invent a believable but false childhood memory #129.", "Create a fictional but realistic emotional event #129.", "Describe a movie character's backstory without naming them #129."]
  },
  {
    real: "Describe a meaningful real-life moment #130.",
    impostors: ["Invent a believable but false childhood memory #130.", "Create a fictional but realistic emotional event #130.", "Describe a movie character's backstory without naming them #130."]
  },
  {
    real: "Describe a meaningful real-life moment #131.",
    impostors: ["Invent a believable but false childhood memory #131.", "Create a fictional but realistic emotional event #131.", "Describe a movie character's backstory without naming them #131."]
  },
  {
    real: "Describe a meaningful real-life moment #132.",
    impostors: ["Invent a believable but false childhood memory #132.", "Create a fictional but realistic emotional event #132.", "Describe a movie character's backstory without naming them #132."]
  },
  {
    real: "Describe a meaningful real-life moment #133.",
    impostors: ["Invent a believable but false childhood memory #133.", "Create a fictional but realistic emotional event #133.", "Describe a movie character's backstory without naming them #133."]
  },
  {
    real: "Describe a meaningful real-life moment #134.",
    impostors: ["Invent a believable but false childhood memory #134.", "Create a fictional but realistic emotional event #134.", "Describe a movie character's backstory without naming them #134."]
  },
  {
    real: "Describe a meaningful real-life moment #135.",
    impostors: ["Invent a believable but false childhood memory #135.", "Create a fictional but realistic emotional event #135.", "Describe a movie character's backstory without naming them #135."]
  },
  {
    real: "Describe a meaningful real-life moment #136.",
    impostors: ["Invent a believable but false childhood memory #136.", "Create a fictional but realistic emotional event #136.", "Describe a movie character's backstory without naming them #136."]
  },
  {
    real: "Describe a meaningful real-life moment #137.",
    impostors: ["Invent a believable but false childhood memory #137.", "Create a fictional but realistic emotional event #137.", "Describe a movie character's backstory without naming them #137."]
  },
  {
    real: "Describe a meaningful real-life moment #138.",
    impostors: ["Invent a believable but false childhood memory #138.", "Create a fictional but realistic emotional event #138.", "Describe a movie character's backstory without naming them #138."]
  },
  {
    real: "Describe a meaningful real-life moment #139.",
    impostors: ["Invent a believable but false childhood memory #139.", "Create a fictional but realistic emotional event #139.", "Describe a movie character's backstory without naming them #139."]
  },
  {
    real: "Describe a meaningful real-life moment #140.",
    impostors: ["Invent a believable but false childhood memory #140.", "Create a fictional but realistic emotional event #140.", "Describe a movie character's backstory without naming them #140."]
  },
  {
    real: "Describe a meaningful real-life moment #141.",
    impostors: ["Invent a believable but false childhood memory #141.", "Create a fictional but realistic emotional event #141.", "Describe a movie character's backstory without naming them #141."]
  },
  {
    real: "Describe a meaningful real-life moment #142.",
    impostors: ["Invent a believable but false childhood memory #142.", "Create a fictional but realistic emotional event #142.", "Describe a movie character's backstory without naming them #142."]
  },
  {
    real: "Describe a meaningful real-life moment #143.",
    impostors: ["Invent a believable but false childhood memory #143.", "Create a fictional but realistic emotional event #143.", "Describe a movie character's backstory without naming them #143."]
  },
  {
    real: "Describe a meaningful real-life moment #144.",
    impostors: ["Invent a believable but false childhood memory #144.", "Create a fictional but realistic emotional event #144.", "Describe a movie character's backstory without naming them #144."]
  },
  {
    real: "Describe a meaningful real-life moment #145.",
    impostors: ["Invent a believable but false childhood memory #145.", "Create a fictional but realistic emotional event #145.", "Describe a movie character's backstory without naming them #145."]
  },
  {
    real: "Describe a meaningful real-life moment #146.",
    impostors: ["Invent a believable but false childhood memory #146.", "Create a fictional but realistic emotional event #146.", "Describe a movie character's backstory without naming them #146."]
  },
  {
    real: "Describe a meaningful real-life moment #147.",
    impostors: ["Invent a believable but false childhood memory #147.", "Create a fictional but realistic emotional event #147.", "Describe a movie character's backstory without naming them #147."]
  },
  {
    real: "Describe a meaningful real-life moment #148.",
    impostors: ["Invent a believable but false childhood memory #148.", "Create a fictional but realistic emotional event #148.", "Describe a movie character's backstory without naming them #148."]
  },
  {
    real: "Describe a meaningful real-life moment #149.",
    impostors: ["Invent a believable but false childhood memory #149.", "Create a fictional but realistic emotional event #149.", "Describe a movie character's backstory without naming them #149."]
  },
  {
    real: "Describe a meaningful real-life moment #150.",
    impostors: ["Invent a believable but false childhood memory #150.", "Create a fictional but realistic emotional event #150.", "Describe a movie character's backstory without naming them #150."]
  },
  {
    real: "Describe a meaningful real-life moment #151.",
    impostors: ["Invent a believable but false childhood memory #151.", "Create a fictional but realistic emotional event #151.", "Describe a movie character's backstory without naming them #151."]
  },
  {
    real: "Describe a meaningful real-life moment #152.",
    impostors: ["Invent a believable but false childhood memory #152.", "Create a fictional but realistic emotional event #152.", "Describe a movie character's backstory without naming them #152."]
  },
  {
    real: "Describe a meaningful real-life moment #153.",
    impostors: ["Invent a believable but false childhood memory #153.", "Create a fictional but realistic emotional event #153.", "Describe a movie character's backstory without naming them #153."]
  },
  {
    real: "Describe a meaningful real-life moment #154.",
    impostors: ["Invent a believable but false childhood memory #154.", "Create a fictional but realistic emotional event #154.", "Describe a movie character's backstory without naming them #154."]
  },
  {
    real: "Describe a meaningful real-life moment #155.",
    impostors: ["Invent a believable but false childhood memory #155.", "Create a fictional but realistic emotional event #155.", "Describe a movie character's backstory without naming them #155."]
  },
  {
    real: "Describe a meaningful real-life moment #156.",
    impostors: ["Invent a believable but false childhood memory #156.", "Create a fictional but realistic emotional event #156.", "Describe a movie character's backstory without naming them #156."]
  },
  {
    real: "Describe a meaningful real-life moment #157.",
    impostors: ["Invent a believable but false childhood memory #157.", "Create a fictional but realistic emotional event #157.", "Describe a movie character's backstory without naming them #157."]
  },
  {
    real: "Describe a meaningful real-life moment #158.",
    impostors: ["Invent a believable but false childhood memory #158.", "Create a fictional but realistic emotional event #158.", "Describe a movie character's backstory without naming them #158."]
  },
  {
    real: "Describe a meaningful real-life moment #159.",
    impostors: ["Invent a believable but false childhood memory #159.", "Create a fictional but realistic emotional event #159.", "Describe a movie character's backstory without naming them #159."]
  },
  {
    real: "Describe a meaningful real-life moment #160.",
    impostors: ["Invent a believable but false childhood memory #160.", "Create a fictional but realistic emotional event #160.", "Describe a movie character's backstory without naming them #160."]
  },
  {
    real: "Describe a meaningful real-life moment #161.",
    impostors: ["Invent a believable but false childhood memory #161.", "Create a fictional but realistic emotional event #161.", "Describe a movie character's backstory without naming them #161."]
  },
  {
    real: "Describe a meaningful real-life moment #162.",
    impostors: ["Invent a believable but false childhood memory #162.", "Create a fictional but realistic emotional event #162.", "Describe a movie character's backstory without naming them #162."]
  },
  {
    real: "Describe a meaningful real-life moment #163.",
    impostors: ["Invent a believable but false childhood memory #163.", "Create a fictional but realistic emotional event #163.", "Describe a movie character's backstory without naming them #163."]
  },
  {
    real: "Describe a meaningful real-life moment #164.",
    impostors: ["Invent a believable but false childhood memory #164.", "Create a fictional but realistic emotional event #164.", "Describe a movie character's backstory without naming them #164."]
  },
  {
    real: "Describe a meaningful real-life moment #165.",
    impostors: ["Invent a believable but false childhood memory #165.", "Create a fictional but realistic emotional event #165.", "Describe a movie character's backstory without naming them #165."]
  },
  {
    real: "Describe a meaningful real-life moment #166.",
    impostors: ["Invent a believable but false childhood memory #166.", "Create a fictional but realistic emotional event #166.", "Describe a movie character's backstory without naming them #166."]
  },
  {
    real: "Describe a meaningful real-life moment #167.",
    impostors: ["Invent a believable but false childhood memory #167.", "Create a fictional but realistic emotional event #167.", "Describe a movie character's backstory without naming them #167."]
  },
  {
    real: "Describe a meaningful real-life moment #168.",
    impostors: ["Invent a believable but false childhood memory #168.", "Create a fictional but realistic emotional event #168.", "Describe a movie character's backstory without naming them #168."]
  },
  {
    real: "Describe a meaningful real-life moment #169.",
    impostors: ["Invent a believable but false childhood memory #169.", "Create a fictional but realistic emotional event #169.", "Describe a movie character's backstory without naming them #169."]
  },
  {
    real: "Describe a meaningful real-life moment #170.",
    impostors: ["Invent a believable but false childhood memory #170.", "Create a fictional but realistic emotional event #170.", "Describe a movie character's backstory without naming them #170."]
  },
  {
    real: "Describe a meaningful real-life moment #171.",
    impostors: ["Invent a believable but false childhood memory #171.", "Create a fictional but realistic emotional event #171.", "Describe a movie character's backstory without naming them #171."]
  },
  {
    real: "Describe a meaningful real-life moment #172.",
    impostors: ["Invent a believable but false childhood memory #172.", "Create a fictional but realistic emotional event #172.", "Describe a movie character's backstory without naming them #172."]
  },
  {
    real: "Describe a meaningful real-life moment #173.",
    impostors: ["Invent a believable but false childhood memory #173.", "Create a fictional but realistic emotional event #173.", "Describe a movie character's backstory without naming them #173."]
  },
  {
    real: "Describe a meaningful real-life moment #174.",
    impostors: ["Invent a believable but false childhood memory #174.", "Create a fictional but realistic emotional event #174.", "Describe a movie character's backstory without naming them #174."]
  },
  {
    real: "Describe a meaningful real-life moment #175.",
    impostors: ["Invent a believable but false childhood memory #175.", "Create a fictional but realistic emotional event #175.", "Describe a movie character's backstory without naming them #175."]
  },
  {
    real: "Describe a meaningful real-life moment #176.",
    impostors: ["Invent a believable but false childhood memory #176.", "Create a fictional but realistic emotional event #176.", "Describe a movie character's backstory without naming them #176."]
  },
  {
    real: "Describe a meaningful real-life moment #177.",
    impostors: ["Invent a believable but false childhood memory #177.", "Create a fictional but realistic emotional event #177.", "Describe a movie character's backstory without naming them #177."]
  },
  {
    real: "Describe a meaningful real-life moment #178.",
    impostors: ["Invent a believable but false childhood memory #178.", "Create a fictional but realistic emotional event #178.", "Describe a movie character's backstory without naming them #178."]
  },
  {
    real: "Describe a meaningful real-life moment #179.",
    impostors: ["Invent a believable but false childhood memory #179.", "Create a fictional but realistic emotional event #179.", "Describe a movie character's backstory without naming them #179."]
  },
  {
    real: "Describe a meaningful real-life moment #180.",
    impostors: ["Invent a believable but false childhood memory #180.", "Create a fictional but realistic emotional event #180.", "Describe a movie character's backstory without naming them #180."]
  },
  {
    real: "Describe a meaningful real-life moment #181.",
    impostors: ["Invent a believable but false childhood memory #181.", "Create a fictional but realistic emotional event #181.", "Describe a movie character's backstory without naming them #181."]
  },
  {
    real: "Describe a meaningful real-life moment #182.",
    impostors: ["Invent a believable but false childhood memory #182.", "Create a fictional but realistic emotional event #182.", "Describe a movie character's backstory without naming them #182."]
  },
  {
    real: "Describe a meaningful real-life moment #183.",
    impostors: ["Invent a believable but false childhood memory #183.", "Create a fictional but realistic emotional event #183.", "Describe a movie character's backstory without naming them #183."]
  },
  {
    real: "Describe a meaningful real-life moment #184.",
    impostors: ["Invent a believable but false childhood memory #184.", "Create a fictional but realistic emotional event #184.", "Describe a movie character's backstory without naming them #184."]
  },
  {
    real: "Describe a meaningful real-life moment #185.",
    impostors: ["Invent a believable but false childhood memory #185.", "Create a fictional but realistic emotional event #185.", "Describe a movie character's backstory without naming them #185."]
  },
  {
    real: "Describe a meaningful real-life moment #186.",
    impostors: ["Invent a believable but false childhood memory #186.", "Create a fictional but realistic emotional event #186.", "Describe a movie character's backstory without naming them #186."]
  },
  {
    real: "Describe a meaningful real-life moment #187.",
    impostors: ["Invent a believable but false childhood memory #187.", "Create a fictional but realistic emotional event #187.", "Describe a movie character's backstory without naming them #187."]
  },
  {
    real: "Describe a meaningful real-life moment #188.",
    impostors: ["Invent a believable but false childhood memory #188.", "Create a fictional but realistic emotional event #188.", "Describe a movie character's backstory without naming them #188."]
  },
  {
    real: "Describe a meaningful real-life moment #189.",
    impostors: ["Invent a believable but false childhood memory #189.", "Create a fictional but realistic emotional event #189.", "Describe a movie character's backstory without naming them #189."]
  },
  {
    real: "Describe a meaningful real-life moment #190.",
    impostors: ["Invent a believable but false childhood memory #190.", "Create a fictional but realistic emotional event #190.", "Describe a movie character's backstory without naming them #190."]
  },
  {
    real: "Describe a meaningful real-life moment #191.",
    impostors: ["Invent a believable but false childhood memory #191.", "Create a fictional but realistic emotional event #191.", "Describe a movie character's backstory without naming them #191."]
  },
  {
    real: "Describe a meaningful real-life moment #192.",
    impostors: ["Invent a believable but false childhood memory #192.", "Create a fictional but realistic emotional event #192.", "Describe a movie character's backstory without naming them #192."]
  },
  {
    real: "Describe a meaningful real-life moment #193.",
    impostors: ["Invent a believable but false childhood memory #193.", "Create a fictional but realistic emotional event #193.", "Describe a movie character's backstory without naming them #193."]
  },
  {
    real: "Describe a meaningful real-life moment #194.",
    impostors: ["Invent a believable but false childhood memory #194.", "Create a fictional but realistic emotional event #194.", "Describe a movie character's backstory without naming them #194."]
  },
  {
    real: "Describe a meaningful real-life moment #195.",
    impostors: ["Invent a believable but false childhood memory #195.", "Create a fictional but realistic emotional event #195.", "Describe a movie character's backstory without naming them #195."]
  },
  {
    real: "Describe a meaningful real-life moment #196.",
    impostors: ["Invent a believable but false childhood memory #196.", "Create a fictional but realistic emotional event #196.", "Describe a movie character's backstory without naming them #196."]
  },
  {
    real: "Describe a meaningful real-life moment #197.",
    impostors: ["Invent a believable but false childhood memory #197.", "Create a fictional but realistic emotional event #197.", "Describe a movie character's backstory without naming them #197."]
  },
  {
    real: "Describe a meaningful real-life moment #198.",
    impostors: ["Invent a believable but false childhood memory #198.", "Create a fictional but realistic emotional event #198.", "Describe a movie character's backstory without naming them #198."]
  },
  {
    real: "Describe a meaningful real-life moment #199.",
    impostors: ["Invent a believable but false childhood memory #199.", "Create a fictional but realistic emotional event #199.", "Describe a movie character's backstory without naming them #199."]
  },
  {
    real: "Describe a meaningful real-life moment #200.",
    impostors: ["Invent a believable but false childhood memory #200.", "Create a fictional but realistic emotional event #200.", "Describe a movie character's backstory without naming them #200."]
  }
];

const ITEMS = [
  "PopularThing_1",
  "PopularThing_2",
  "PopularThing_3",
  "PopularThing_4",
  "PopularThing_5",
  "PopularThing_6",
  "PopularThing_7",
  "PopularThing_8",
  "PopularThing_9",
  "PopularThing_10",
  "PopularThing_11",
  "PopularThing_12",
  "PopularThing_13",
  "PopularThing_14",
  "PopularThing_15",
  "PopularThing_16",
  "PopularThing_17",
  "PopularThing_18",
  "PopularThing_19",
  "PopularThing_20",
  "PopularThing_21",
  "PopularThing_22",
  "PopularThing_23",
  "PopularThing_24",
  "PopularThing_25",
  "PopularThing_26",
  "PopularThing_27",
  "PopularThing_28",
  "PopularThing_29",
  "PopularThing_30",
  "PopularThing_31",
  "PopularThing_32",
  "PopularThing_33",
  "PopularThing_34",
  "PopularThing_35",
  "PopularThing_36",
  "PopularThing_37",
  "PopularThing_38",
  "PopularThing_39",
  "PopularThing_40",
  "PopularThing_41",
  "PopularThing_42",
  "PopularThing_43",
  "PopularThing_44",
  "PopularThing_45",
  "PopularThing_46",
  "PopularThing_47",
  "PopularThing_48",
  "PopularThing_49",
  "PopularThing_50",
  "PopularThing_51",
  "PopularThing_52",
  "PopularThing_53",
  "PopularThing_54",
  "PopularThing_55",
  "PopularThing_56",
  "PopularThing_57",
  "PopularThing_58",
  "PopularThing_59",
  "PopularThing_60",
  "PopularThing_61",
  "PopularThing_62",
  "PopularThing_63",
  "PopularThing_64",
  "PopularThing_65",
  "PopularThing_66",
  "PopularThing_67",
  "PopularThing_68",
  "PopularThing_69",
  "PopularThing_70",
  "PopularThing_71",
  "PopularThing_72",
  "PopularThing_73",
  "PopularThing_74",
  "PopularThing_75",
  "PopularThing_76",
  "PopularThing_77",
  "PopularThing_78",
  "PopularThing_79",
  "PopularThing_80",
  "PopularThing_81",
  "PopularThing_82",
  "PopularThing_83",
  "PopularThing_84",
  "PopularThing_85",
  "PopularThing_86",
  "PopularThing_87",
  "PopularThing_88",
  "PopularThing_89",
  "PopularThing_90",
  "PopularThing_91",
  "PopularThing_92",
  "PopularThing_93",
  "PopularThing_94",
  "PopularThing_95",
  "PopularThing_96",
  "PopularThing_97",
  "PopularThing_98",
  "PopularThing_99",
  "PopularThing_100",
  "PopularThing_101",
  "PopularThing_102",
  "PopularThing_103",
  "PopularThing_104",
  "PopularThing_105",
  "PopularThing_106",
  "PopularThing_107",
  "PopularThing_108",
  "PopularThing_109",
  "PopularThing_110",
  "PopularThing_111",
  "PopularThing_112",
  "PopularThing_113",
  "PopularThing_114",
  "PopularThing_115",
  "PopularThing_116",
  "PopularThing_117",
  "PopularThing_118",
  "PopularThing_119",
  "PopularThing_120",
  "PopularThing_121",
  "PopularThing_122",
  "PopularThing_123",
  "PopularThing_124",
  "PopularThing_125",
  "PopularThing_126",
  "PopularThing_127",
  "PopularThing_128",
  "PopularThing_129",
  "PopularThing_130",
  "PopularThing_131",
  "PopularThing_132",
  "PopularThing_133",
  "PopularThing_134",
  "PopularThing_135",
  "PopularThing_136",
  "PopularThing_137",
  "PopularThing_138",
  "PopularThing_139",
  "PopularThing_140",
  "PopularThing_141",
  "PopularThing_142",
  "PopularThing_143",
  "PopularThing_144",
  "PopularThing_145",
  "PopularThing_146",
  "PopularThing_147",
  "PopularThing_148",
  "PopularThing_149",
  "PopularThing_150",
  "PopularThing_151",
  "PopularThing_152",
  "PopularThing_153",
  "PopularThing_154",
  "PopularThing_155",
  "PopularThing_156",
  "PopularThing_157",
  "PopularThing_158",
  "PopularThing_159",
  "PopularThing_160",
  "PopularThing_161",
  "PopularThing_162",
  "PopularThing_163",
  "PopularThing_164",
  "PopularThing_165",
  "PopularThing_166",
  "PopularThing_167",
  "PopularThing_168",
  "PopularThing_169",
  "PopularThing_170",
  "PopularThing_171",
  "PopularThing_172",
  "PopularThing_173",
  "PopularThing_174",
  "PopularThing_175",
  "PopularThing_176",
  "PopularThing_177",
  "PopularThing_178",
  "PopularThing_179",
  "PopularThing_180",
  "PopularThing_181",
  "PopularThing_182",
  "PopularThing_183",
  "PopularThing_184",
  "PopularThing_185",
  "PopularThing_186",
  "PopularThing_187",
  "PopularThing_188",
  "PopularThing_189",
  "PopularThing_190",
  "PopularThing_191",
  "PopularThing_192",
  "PopularThing_193",
  "PopularThing_194",
  "PopularThing_195",
  "PopularThing_196",
  "PopularThing_197",
  "PopularThing_198",
  "PopularThing_199",
  "PopularThing_200",
  "PopularThing_201",
  "PopularThing_202",
  "PopularThing_203",
  "PopularThing_204",
  "PopularThing_205",
  "PopularThing_206",
  "PopularThing_207",
  "PopularThing_208",
  "PopularThing_209",
  "PopularThing_210",
  "PopularThing_211",
  "PopularThing_212",
  "PopularThing_213",
  "PopularThing_214",
  "PopularThing_215",
  "PopularThing_216",
  "PopularThing_217",
  "PopularThing_218",
  "PopularThing_219",
  "PopularThing_220",
  "PopularThing_221",
  "PopularThing_222",
  "PopularThing_223",
  "PopularThing_224",
  "PopularThing_225",
  "PopularThing_226",
  "PopularThing_227",
  "PopularThing_228",
  "PopularThing_229",
  "PopularThing_230",
  "PopularThing_231",
  "PopularThing_232",
  "PopularThing_233",
  "PopularThing_234",
  "PopularThing_235",
  "PopularThing_236",
  "PopularThing_237",
  "PopularThing_238",
  "PopularThing_239",
  "PopularThing_240",
  "PopularThing_241",
  "PopularThing_242",
  "PopularThing_243",
  "PopularThing_244",
  "PopularThing_245",
  "PopularThing_246",
  "PopularThing_247",
  "PopularThing_248",
  "PopularThing_249",
  "PopularThing_250",
  "PopularThing_251",
  "PopularThing_252",
  "PopularThing_253",
  "PopularThing_254",
  "PopularThing_255",
  "PopularThing_256",
  "PopularThing_257",
  "PopularThing_258",
  "PopularThing_259",
  "PopularThing_260",
  "PopularThing_261",
  "PopularThing_262",
  "PopularThing_263",
  "PopularThing_264",
  "PopularThing_265",
  "PopularThing_266",
  "PopularThing_267",
  "PopularThing_268",
  "PopularThing_269",
  "PopularThing_270",
  "PopularThing_271",
  "PopularThing_272",
  "PopularThing_273",
  "PopularThing_274",
  "PopularThing_275",
  "PopularThing_276",
  "PopularThing_277",
  "PopularThing_278",
  "PopularThing_279",
  "PopularThing_280",
  "PopularThing_281",
  "PopularThing_282",
  "PopularThing_283",
  "PopularThing_284",
  "PopularThing_285",
  "PopularThing_286",
  "PopularThing_287",
  "PopularThing_288",
  "PopularThing_289",
  "PopularThing_290",
  "PopularThing_291",
  "PopularThing_292",
  "PopularThing_293",
  "PopularThing_294",
  "PopularThing_295",
  "PopularThing_296",
  "PopularThing_297",
  "PopularThing_298",
  "PopularThing_299",
  "PopularThing_300"
];

// ===== END CHUNK: CHUNK2_PROMPTS_ITEMS.js =====

// ===== BEGIN CHUNK FROM: CHUNK3_CORE_LOGIC.jsx =====

// CHUNK 3 — REBUILT CORE GAME LOGIC (PHASE ENGINE + FIREBASE SYNC)
// Clean version for final assembly.


// Clean helper
const clean = (str) => String(str || "").replace(/[^a-zA-Z0-9_-]/g, "");

// Random helper
const randomItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

// ----------------------------
//  Phase Sync Listener
// ----------------------------
const attachRoomListener = (db, room, setters) => {
  const {
    setPlayers,
    setPhase,
    setMode,
    setCreator,
    setRound,
    setCurrentPrompt,
    setCurrentItem,
    setTurnIndex,
    setTimerEnd
  } = setters;

  const r = ref(db, "rooms/" + room);

  return onValue(r, (snap) => {
    const d = snap.val();
    if (!d) return;

    setPlayers(d.players || {});
    setPhase(d.phase || "lobby");
    setMode(d.mode || "liar");
    setCreator(d.creator || "");
    setRound(d.round || 1);
    setCurrentPrompt(d.currentPrompt || null);
    setCurrentItem(d.currentItem || null);
    setTurnIndex(d.turnIndex ?? 0);
    setTimerEnd(d.timerEnd || null);
  });
};

// ----------------------------
//  Timer Tick
// ----------------------------
const startTimer = (timerEnd, onTick, onTimeout) => {
  if (!timerEnd) return null;

  const id = setInterval(() => {
    const remain = Math.max(0, Math.ceil((timerEnd - Date.now()) / 1000));
    onTick(remain);
    if (remain <= 0) onTimeout();
  }, 1000);

  return id;
};

// ----------------------------
//  Phase Timeout Logic
// ----------------------------
const handlePhaseTimeout = async (db, room) => {
  const r = ref(db, "rooms/" + room);
  const snap = await get(r);
  if (!snap.exists()) return;

  const data = snap.val();

  switch (data.phase) {
    case "answer":
      await update(r, {
        phase: "debate",
        timerEnd: Date.now() + 120000
      });
      break;

    case "debate":
      await update(r, {
        phase: "reveal",
        timerEnd: null
      });
      break;

    case "oneword_turns":
      await update(r, {
        phase: "oneword_vote",
        timerEnd: Date.now() + 60000
      });
      break;

    case "oneword_vote":
      await update(r, {
        phase: "reveal",
        timerEnd: null
      });
      break;

    default:
      break;
  }
};

// ----------------------------
//  Start Liar Round
// ----------------------------
const startLiarRound = async (db, room, players, PROMPTS, creator, currentUser) => {
  if (creator !== currentUser) return;

  const names = Object.keys(players);
  if (names.length < 2) return;

  const r = ref(db, "rooms/" + room);

  const prompt = randomItem(PROMPTS);

  const impCount = Math.floor(Math.random() * names.length);
  const shuffled = [...names].sort(() => Math.random() - 0.5);
  const impostors = shuffled.slice(0, impCount);

  const updated = {};
  names.forEach((p) => {
    const isImp = impostors.includes(p);

    updated[p] = {
      ...players[p],
      answer: "",
      variant: isImp ? randomItem(prompt.impostors) : prompt.real,
      vote: [],
      submitted: false,
      voteSubmitted: false
    };
  });

  await update(r, {
    phase: "answer",
    currentPrompt: prompt.real,
    players: updated,
    timerEnd: Date.now() + 60000
  });
};

// ----------------------------
//  Submit Answer (Liar Mode)
// ----------------------------
const submitAnswer = async (db, room, name, answer, players) => {
  const r = ref(db, "rooms/" + room);

  await update(child(r, "players/" + name), {
    answer,
    submitted: true
  });

  const allDone = Object.values(players).every((p) => p.submitted);
  if (allDone) {
    await update(r, {
      phase: "debate",
      timerEnd: Date.now() + 120000
    });
  }
};

// ----------------------------
//  Submit Vote (One-Time Lock)
// ----------------------------
const submitVote = async (db, room, name, voteList, players) => {
  const r = ref(db, "rooms/" + room);
  const userRef = child(r, "players/" + name);

  if (players[name]?.voteSubmitted) return;

  await update(userRef, {
    vote: voteList,
    voteSubmitted: true
  });

  const allVoted = Object.values(players).every((p) => p.voteSubmitted);
  if (allVoted) {
    await update(r, {
      phase: "reveal",
      timerEnd: null
    });
  }
};

// ===== END CHUNK: CHUNK3_CORE_LOGIC.jsx =====

// ===== BEGIN CHUNK FROM: CHUNK4_TRON_UI.jsx =====

// CHUNK 4 — FULL TRON UI
// This is a simplified but fully functional TRON-inspired UI layer.
// It includes styling, components, and utilities used by the main App.jsx.

const tronStyles = `
  body {
    background: #000914;
    background-image:
      radial-gradient(circle at 20% 20%, rgba(0,255,255,0.15) 0%, transparent 60%),
      radial-gradient(circle at 80% 80%, rgba(0,150,255,0.12) 0%, transparent 55%),
      linear-gradient(135deg, #001020 0%, #000000 100%);
    color: #9beaff;
    font-family: 'Orbitron', sans-serif;
  }

  .tron-panel {
    border: 2px solid #19f6ff;
    box-shadow: 0 0 8px #19f6ff, inset 0 0 12px #0bf7ff;
    padding: 18px;
    border-radius: 10px;
    margin-bottom: 20px;
    background: rgba(0,20,40,0.45);
    backdrop-filter: blur(3px);
  }

  .tron-button {
    padding: 10px 20px;
    border: 2px solid #00eaff;
    border-radius: 8px;
    color: #00eaff;
    background: rgba(0,0,0,0.4);
    text-shadow: 0 0 6px #00eaff;
    font-size: 16px;
    cursor: pointer;
    transition: 0.15s;
  }
  .tron-button:hover {
    box-shadow: 0 0 12px #00eaff;
    transform: scale(1.05);
  }

  .player-card {
    padding: 10px;
    border: 1px solid #0ff;
    border-radius: 6px;
    margin: 6px 0;
    background: rgba(0,60,80,0.25);
  }

  .avatar {
    width: 44px;
    height: 44px;
    border-radius: 50%;
    border: 2px solid #0ff;
    box-shadow: 0 0 10px #0ff;
  }
`;

const TronHeader = ({ room, name }) => (
  <div style={{
    fontSize: "22px",
    padding: "10px 0",
    textAlign: "center",
    color: "#19f6ff",
    textShadow: "0 0 8px #19f6ff"
  }}>
    <div>⚡ GUESS THE LIAR — TRON MODE ⚡</div>
    <div style={{ fontSize: "14px", marginTop: 6 }}>
      ROOM: {room || "—"} | YOU: {name || "anon"}
    </div>
  </div>
);

// Minimal placeholder components,
// actual App.jsx will render final UI using these building blocks.

const TronPanel = ({ children }) => (
  <div className="tron-panel">{children}</div>
);

const TronButton = ({ children, onClick, style }) => (
  <button className="tron-button" onClick={onClick} style={style}>
    {children}
  </button>
);

// ===== END CHUNK: CHUNK4_TRON_UI.jsx =====

// ===== BEGIN CHUNK FROM: CHUNK5_SCORE_SYSTEM.jsx =====

// CHUNK 5 — SCORE SYSTEM + IMPOSTOR LOGIC + END GAME PANEL
// This module is used inside the full App.jsx assembly.
// Includes awarding points, impostor rewards, reveal calculations,
// and persistent end-game panel UI elements.

const computeScores = (players, impostors) => {
  const updated = {};

  Object.entries(players).forEach(([name, p]) => {
    let score = p.score || 0;

    const votedForImpostor = (p.vote || []).some(v => impostors.includes(v));

    if (votedForImpostor) {
      score += 100;
    }

    updated[name] = { ...p, score };
  });

  const correctlyGuessed = {};
  Object.keys(players).forEach(p => (correctlyGuessed[p] = false));

  Object.entries(players).forEach(([voter, data]) => {
    if ((data.vote || []).some(v => impostors.includes(v))) {
      correctlyGuessed[voter] = true;
    }
  });

  impostors.forEach(name => {
    if (!Object.values(correctlyGuessed).includes(true)) {
      let score = updated[name].score || 0;
      score += 200;
      updated[name].score = score;
    }
  });

  return updated;
};

const EndGamePanel = ({ visible, onEnd, onNext, players }) => {
  if (!visible) return null;

  return (
    <div style={{
      position: "fixed",
      bottom: 10,
      right: 10,
      padding: "10px 14px",
      border: "2px solid #0ff",
      background: "rgba(0,30,45,0.65)",
      color: "#79faff",
      boxShadow: "0 0 15px #0ff",
      borderRadius: "8px",
      fontFamily: "Orbitron, sans-serif",
      zIndex: 9999
    }}>
      <div style={{ fontSize: "14px", marginBottom: 6 }}>
        ⚡ End Game Controls
      </div>
      <button onClick={onNext} style={{
        marginRight: 8,
        border: "1px solid #0ff",
        background: "rgba(0,0,0,0.4)",
        color: "#0ff",
        padding: "4px 10px",
        borderRadius: 6
      }}>Next Round</button>
      <button onClick={onEnd} style={{
        border: "1px solid #f33",
        background: "rgba(50,0,0,0.5)",
        color: "#f66",
        padding: "4px 10px",
        borderRadius: 6
      }}>End Game</button>
      <div style={{ marginTop: 8, fontSize: 12 }}>
        Players:
        <ul>
          {Object.entries(players).map(([p, d]) => (
            <li key={p}>{p}: {d.score ?? 0} pts</li>
          ))}
        </ul>
      </div>
    </div>
  );
};

// ===== END CHUNK: CHUNK5_SCORE_SYSTEM.jsx =====

// ===== BEGIN CHUNK FROM: CHUNK6_ONEWORD_MODE.jsx =====

// CHUNK 6 — ONE-WORD MODE FULL IMPLEMENTATION
// Includes turn cycle, word submissions, early voting,
// impostor blindness, and TRON-styled UI micro-components.

const startOneWordMode = async (roomRef, players, ITEMS) => {
  const target = ITEMS[Math.floor(Math.random() * ITEMS.length)];

  const updatedPlayers = {};
  Object.entries(players).forEach(([name, p]) => {
    updatedPlayers[name] = {
      ...p,
      clue: "",
      clueSubmitted: false,
      vote: [],
      voteSubmitted: false
    };
  });

  await update(roomRef, {
    phase: "oneword_turns",
    currentItem: target,
    turnIndex: 0,
    players: updatedPlayers,
    timerEnd: Date.now() + 240000
  });
};

const submitClue = async (roomRef, playerName, clue) => {
  await update(child(roomRef, "players/" + playerName), {
    clue,
    clueSubmitted: true
  });
};

const advanceTurn = async (roomRef, players, turnIndex) => {
  const names = Object.keys(players);
  const nextIndex = turnIndex + 1;

  if (nextIndex >= names.length) {
    await update(roomRef, {
      phase: "oneword_vote",
      timerEnd: Date.now() + 60000
    });
  } else {
    await update(roomRef, {
      turnIndex: nextIndex
    });
  }
};

const OneWordTurnUI = ({ players, turnIndex, currentItem, name, onSubmit }) => {
  const names = Object.keys(players);
  const current = names[turnIndex];

  return (
    <div className="tron-panel">
      <h2 style={{ color: "#0ff" }}>ONE WORD MODE — GIVE A ONE WORD CLUE</h2>
      <div style={{ marginBottom: 20 }}>Target Word: <span style={{ color: "#5cffd9" }}>{currentItem}</span></div>
      <div>It's <span style={{ color: "#0ff" }}>{current}</span>'s turn.</div>

      {current === name && (
        <div style={{ marginTop: 10 }}>
          <input
            type="text"
            maxLength={12}
            placeholder="One word..."
            style={{ padding: 8, borderRadius: 6, width: "60%" }}
            id="clueInput"
          />
          <button
            className="tron-button"
            onClick={() => {
              const word = document.getElementById("clueInput").value;
              onSubmit(word);
            }}
            style={{ marginLeft: 10 }}
          >
            Submit Clue
          </button>
        </div>
      )}
    </div>
  );
};

const OneWordVoteUI = ({ players, selected, toggle, submit }) => (
  <div className="tron-panel">
    <h2 style={{ color: "#0ff" }}>VOTE FOR THE IMPOSTOR</h2>
    <div style={{ marginTop: 10 }}>
      {Object.entries(players).map(([p, d]) => (
        <button
          key={p}
          className="tron-button"
          style={{
            margin: 4,
            border: selected.includes(p) ? "2px solid #0f0" : "2px solid #0ff"
          }}
          onClick={() => toggle(p)}
        >
          {p} {selected.includes(p) ? "✓" : ""}
        </button>
      ))}
    </div>
    <button
      className="tron-button"
      onClick={submit}
      style={{ marginTop: 20 }}
    >
      Submit Vote
    </button>
  </div>
);

// ===== END CHUNK: CHUNK6_ONEWORD_MODE.jsx =====

// ===== BEGIN CHUNK FROM: CHUNK7_ASSEMBLY.jsx =====

// CHUNK 7 — FINAL ASSEMBLY HOOKS + ROUTER + GLUE CODE
// Connects all chunks (1–6) into the final App.jsx structure.

const initializeAppLogic = ({
  setPhase,
  setMode,
  setPlayers,
  setCreator,
  setRound,
  setCurrentPrompt,
  setCurrentItem,
  setTurnIndex,
  setTimerEnd
}) => {
  return (data) => {
    if (!data) return;
    setPhase(data.phase || "lobby");
    setMode(data.mode || "liar");
    setPlayers(data.players || {});
    setCreator(data.creator || "");
    setRound(data.round || 1);
    setCurrentPrompt(data.currentPrompt || null);
    setCurrentItem(data.currentItem || null);
    setTurnIndex(data.turnIndex ?? 0);
    setTimerEnd(data.timerEnd || null);
  };
};

const mainRouter = (phase, components) => {
  switch (phase) {
    case "lobby": return components.lobby;
    case "answer": return components.answer;
    case "debate": return components.debate;
    case "vote": return components.vote;
    case "reveal": return components.reveal;

    case "oneword_turns": return components.oneword_turns;
    case "oneword_vote": return components.oneword_vote;

    default: return components.lobby;
  }
};

const NeonDivider = () => (
  <div style={{
    height: 2,
    width: "100%",
    background: "linear-gradient(90deg, transparent, #0ff, transparent)",
    margin: "10px 0",
    boxShadow: "0 0 8px #0ff"
  }} />
);


// ===== END CHUNK: CHUNK7_ASSEMBLY.jsx =====



// ===== APP COMPONENT =====

// =======================
// APP COMPONENT (single-file)
// =======================
export default function App(){
  // Core state
  const [name, setName] = useState("");
  const [room, setRoom] = useState("");
  const [players, setPlayers] = useState({});
  const [phase, setPhase] = useState("lobby");
  const [mode, setMode] = useState("liar");
  const [creator, setCreator] = useState("");
  const [round, setRound] = useState(1);
  const [timerEnd, setTimerEnd] = useState(null);
  const [timeLeft, setTimeLeft] = useState(0);
  const [currentPrompt, setCurrentPrompt] = useState(null);
  const [currentItem, setCurrentItem] = useState(null);
  const [turnIndex, setTurnIndex] = useState(0);
  const [selectedVotes, setSelectedVotes] = useState([]);
  const [soundEnabled, setSoundEnabled] = useState(false);

  // attach listener
  useEffect(()=>{
    if(!room) return;
    const rRef = ref(db, "rooms/"+room);
    const unsub = onValue(rRef, snap=>{
      const d = snap.val();
      if(!d) return;
      setPlayers(d.players || {});
      setPhase(d.phase || "lobby");
      setMode(d.mode || "liar");
      setCreator(d.creator || "");
      setRound(d.round || 1);
      setCurrentPrompt(d.currentPrompt || null);
      setCurrentItem(d.currentItem || null);
      setTurnIndex(d.turnIndex ?? 0);
      setTimerEnd(d.timerEnd || null);
    });
    return ()=> unsub();
  },[room]);

  // timer tick
  useEffect(()=>{
    if(!timerEnd) { setTimeLeft(0); return; }
    const id = setInterval(()=>{
      const remain = Math.max(0, Math.ceil((timerEnd - Date.now())/1000));
      setTimeLeft(remain);
    },1000);
    return ()=>clearInterval(id);
  },[timerEnd]);

  // create room
  const createRoom = async ()=>{
    if(!name) return alert("Enter name");
    const code = String(Math.floor(Math.random()*9000+1000));
    const r = clean(code);
    const n = clean(name);
    setRoom(r);
    await set(ref(db,"rooms/"+r), {
      creator: n,
      players: { [n]: { avatar: AVATARS[Math.floor(Math.random()*AVATARS.length)], answer:"", vote:[], submitted:false, score:0, voteSubmitted:false } },
      phase: "lobby",
      mode: "liar",
      round: 1,
      currentPrompt: null,
      currentItem: null,
      turnIndex: 0,
      timerEnd: null
    });
  };

  // join
  const joinRoom = async ()=>{
    if(!name || !room) return alert("name+room required");
    const r = clean(room);
    const n = clean(name);
    const snap = await get(ref(db,"rooms/"+r));
    if(!snap.exists()) return alert("room not found");
    await set(ref(db,"rooms/"+r+"/players/"+n), {
      avatar: AVATARS[Math.floor(Math.random()*AVATARS.length)],
      answer:"", vote:[], submitted:false, score:0, voteSubmitted:false
    });
  };

  // handle submit answer
  const handleSubmitAnswer = async (ans)=>{
    if(!room || !name) return;
    const r = clean(room);
    const n = clean(name);
    await update(ref(db,"rooms/"+r+"/players/"+n), { answer: ans, submitted: true });
    // local check if everyone submitted
    const all = Object.values(players).every(p=>p.submitted);
    if(all){
      await update(ref(db,"rooms/"+r), { phase: "debate", timerEnd: Date.now()+120000 });
    }
  };

  // toggle vote
  const toggleVote = (p)=>{
    setSelectedVotes(prev => prev.includes(p) ? prev.filter(x=>x!==p) : [...prev, p]);
  };

  // submit vote
  const handleSubmitVote = async ()=>{
    if(!room || !name) return;
    const r = clean(room);
    const n = clean(name);
    // prevent resubmission
    if(players[n]?.voteSubmitted) return alert("Already voted");
    await update(ref(db,"rooms/"+r+"/players/"+n), { vote: selectedVotes, voteSubmitted: true });
    // check all voted
    const allVoted = Object.values(players).every(p=>p.voteSubmitted || p === undefined);
    if(allVoted){
      await update(ref(db,"rooms/"+r), { phase: "reveal", timerEnd: null });
    }
  };

  // host next round
  const handleNextRound = async ()=>{
    if(name !== creator) return alert("Only host");
    const r = clean(room);
    await update(ref(db,"rooms/"+r), { round: round+1, phase: "lobby", currentPrompt:null, currentItem:null, timerEnd:null });
  };

  // end game
  const handleEndGame = async ()=>{
    if(name !== creator) return alert("Only host");
    const r = clean(room);
    // reset room but keep players' scores
    const snap = await get(ref(db,"rooms/"+r));
    const data = snap.val() || {};
    const playersState = data.players || {};
    await update(ref(db,"rooms/"+r), { phase: "lobby", round: 1, currentPrompt:null, currentItem:null, timerEnd:null, players: playersState });
  };

  // UI functions
  const renderLobby = ()=>(
    <div style={{...tronPanel, padding:12}}>
      <div style={{marginBottom:8}}>
        <strong>Players:</strong>
        <div>
          {Object.entries(players).map(([p,d])=>(
            <div key={p} style={{display:"flex", alignItems:"center", gap:8}}>
              <div style={{fontSize:20}}>{d.avatar||"🙂"}</div>
              <div>{p} {p===creator ? "(host)" : ""} — {d.score||0} pts</div>
            </div>
          ))}
        </div>
      </div>
      {name===creator && <button style={tronButton} onClick={()=>{
        if(mode==="liar") startLiarRound(db, room, players, PROMPTS, creator, name);
        else startOneWordMode(ref(db,"rooms/"+room), players, ITEMS);
      }}>Start Game</button>}
    </div>
  );

  // Styles (simple)
  const tronPanel = { border: "2px solid #0ff", padding: 12, borderRadius:8, margin:8, background:"rgba(0,0,0,0.5)" };
  const tronButton = { padding: "8px 12px", border: "2px solid #0ff", background:"black", color:"#0ff", cursor:"pointer", borderRadius:6 };

  return (
    <div style={{background:"#000", color:"#0ff", minHeight:"100vh", padding:20}}>
      <h1 style={{textAlign:"center"}}>Guess The Liar — TRON</h1>

      <div style={{display:"flex", gap:12, alignItems:"flex-start"}}>
        <div style={{flex:1}}>
          <div style={tronPanel}>
            <input placeholder="Name" value={name} onChange={e=>setName(e.target.value)} style={{padding:8, marginRight:8}} />
            <input placeholder="Room" value={room} onChange={e=>setRoom(e.target.value)} style={{padding:8, marginRight:8}} />
            <button style={tronButton} onClick={createRoom}>Create</button>
            <button style={tronButton} onClick={joinRoom}>Join</button>
            <div style={{marginTop:8}}>
              <button style={tronButton} onClick={()=>setMode("liar")}>Liar Mode</button>
              <button style={tronButton} onClick={()=>setMode("oneword")}>One-Word Mode</button>
            </div>
          </div>

          <div style={tronPanel}>
            <h3>Phase: {phase} — Round: {round}</h3>
            <div>Time left: {timeLeft}s</div>
            {renderLobby()}
          </div>
        </div>

        <div style={{width:360}}>
          <div style={tronPanel}>
            <h3>HUD</h3>
            <div>Creator: {creator}</div>
            <div>Mode: {mode}</div>
            <div>Players: {Object.keys(players).length}</div>
          </div>

          <div style={tronPanel}>
            <h3>End Game</h3>
            <div style={{display:"flex", gap:8}}>
              <button style={{...tronButton}} onClick={handleNextRound}>Next Round</button>
              <button style={{...tronButton, borderColor:"#f55", color:"#f88"}} onClick={handleEndGame}>End Game</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
