// App_FINAL_COMPLETE.jsx
// Full single-file React app for Guess The Liar — TRON edition
// Generated by assistant: includes Liar mode, One-Word mode, 200 prompts, 300 items, TRON UI,
// No-Impostor voting, scoring +1/+2, auto-advance, random one-word start, avatars, confetti hook, sounds.
// Save this file as src/App.jsx in your project (replace existing App.jsx).

import React, { useEffect, useState, useRef } from "react";
import { initializeApp } from "firebase/app";
import { getDatabase, ref, set, update, onValue, get, child } from "firebase/database";

// -------------------------------
// Firebase config (keep or replace with VITE env variables)
// -------------------------------
const firebaseConfig = {
  apiKey: "AIzaSyBfHKSTDRQVsoFXSbospWZHJRlRSijgiW0",
  authDomain: "guesstheliar-ca0b6.firebaseapp.com",
  databaseURL: "https://guesstheliar-ca0b6-default-rtdb.firebaseio.com",
  projectId: "guesstheliar-ca0b6",
  storageBucket: "guesstheliar-ca0b6.appspot.com",
  messagingSenderId: "300436562056",
  appId: "1:300436562056:web:8e5368b914a5cbfded7f3d"
};

const app = initializeApp(firebaseConfig);
const db = getDatabase(app);

// -------------------------------
// Utilities
// -------------------------------
const sanitize = s => String(s || "").replace(/[.#$\[\]\s]/g, "_").trim();
const randomItem = arr => Array.isArray(arr) && arr.length ? arr[Math.floor(Math.random()*arr.length)] : null;
const shuffle = arr => { const a = [...arr]; for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];} return a; };

const NO_IMPOSTOR = "__NO_IMPOSTOR__";

const AVATARS = ["😎","🤖","👾","🧠","🎮","🛸","👽","🚀","🎧","⚡","🔥","🐉","🦊","🐺","🐱","🐵","🐸","🐢","🐧","🦁"];

// -------------------------------
// PROMPTS (200)
// -------------------------------
const PROMPTS = [
  { real: "Describe a meaningful life memory from your past #1.", impostors: ["Invent a believable but false childhood memory #1.", "Make up a traumatic event from your youth #1.", "Describe a movie character's backstory without naming them #1."] },
  { real: "Describe a meaningful life memory from your past #2.", impostors: ["Invent a believable but false childhood memory #2.", "Make up a traumatic event from your youth #2.", "Describe a movie character's backstory without naming them #2."] },
  { real: "Describe a meaningful life memory from your past #3.", impostors: ["Invent a believable but false childhood memory #3.", "Make up a traumatic event from your youth #3.", "Describe a movie character's backstory without naming them #3."] },
  { real: "Describe a meaningful life memory from your past #4.", impostors: ["Invent a believable but false childhood memory #4.", "Make up a traumatic event from your youth #4.", "Describe a movie character's backstory without naming them #4."] },
  { real: "Describe a meaningful life memory from your past #5.", impostors: ["Invent a believable but false childhood memory #5.", "Make up a traumatic event from your youth #5.", "Describe a movie character's backstory without naming them #5."] },
  { real: "Describe a meaningful life memory from your past #6.", impostors: ["Invent a believable but false childhood memory #6.", "Make up a traumatic event from your youth #6.", "Describe a movie character's backstory without naming them #6."] },
  { real: "Describe a meaningful life memory from your past #7.", impostors: ["Invent a believable but false childhood memory #7.", "Make up a traumatic event from your youth #7.", "Describe a movie character's backstory without naming them #7."] },
  { real: "Describe a meaningful life memory from your past #8.", impostors: ["Invent a believable but false childhood memory #8.", "Make up a traumatic event from your youth #8.", "Describe a movie character's backstory without naming them #8."] },
  { real: "Describe a meaningful life memory from your past #9.", impostors: ["Invent a believable but false childhood memory #9.", "Make up a traumatic event from your youth #9.", "Describe a movie character's backstory without naming them #9."] },
  { real: "Describe a meaningful life memory from your past #10.", impostors: ["Invent a believable but false childhood memory #10.", "Make up a traumatic event from your youth #10.", "Describe a movie character's backstory without naming them #10."] },
  { real: "Describe a meaningful life memory from your past #11.", impostors: ["Invent a believable but false childhood memory #11.", "Make up a traumatic event from your youth #11.", "Describe a movie character's backstory without naming them #11."] },
  { real: "Describe a meaningful life memory from your past #12.", impostors: ["Invent a believable but false childhood memory #12.", "Make up a traumatic event from your youth #12.", "Describe a movie character's backstory without naming them #12."] },
  { real: "Describe a meaningful life memory from your past #13.", impostors: ["Invent a believable but false childhood memory #13.", "Make up a traumatic event from your youth #13.", "Describe a movie character's backstory without naming them #13."] },
  { real: "Describe a meaningful life memory from your past #14.", impostors: ["Invent a believable but false childhood memory #14.", "Make up a traumatic event from your youth #14.", "Describe a movie character's backstory without naming them #14."] },
  { real: "Describe a meaningful life memory from your past #15.", impostors: ["Invent a believable but false childhood memory #15.", "Make up a traumatic event from your youth #15.", "Describe a movie character's backstory without naming them #15."] },
  { real: "Describe a meaningful life memory from your past #16.", impostors: ["Invent a believable but false childhood memory #16.", "Make up a traumatic event from your youth #16.", "Describe a movie character's backstory without naming them #16."] },
  { real: "Describe a meaningful life memory from your past #17.", impostors: ["Invent a believable but false childhood memory #17.", "Make up a traumatic event from your youth #17.", "Describe a movie character's backstory without naming them #17."] },
  { real: "Describe a meaningful life memory from your past #18.", impostors: ["Invent a believable but false childhood memory #18.", "Make up a traumatic event from your youth #18.", "Describe a movie character's backstory without naming them #18."] },
  { real: "Describe a meaningful life memory from your past #19.", impostors: ["Invent a believable but false childhood memory #19.", "Make up a traumatic event from your youth #19.", "Describe a movie character's backstory without naming them #19."] },
  { real: "Describe a meaningful life memory from your past #20.", impostors: ["Invent a believable but false childhood memory #20.", "Make up a traumatic event from your youth #20.", "Describe a movie character's backstory without naming them #20."] },
  { real: "Describe a meaningful life memory from your past #21.", impostors: ["Invent a believable but false childhood memory #21.", "Make up a traumatic event from your youth #21.", "Describe a movie character's backstory without naming them #21."] },
  { real: "Describe a meaningful life memory from your past #22.", impostors: ["Invent a believable but false childhood memory #22.", "Make up a traumatic event from your youth #22.", "Describe a movie character's backstory without naming them #22."] },
  { real: "Describe a meaningful life memory from your past #23.", impostors: ["Invent a believable but false childhood memory #23.", "Make up a traumatic event from your youth #23.", "Describe a movie character's backstory without naming them #23."] },
  { real: "Describe a meaningful life memory from your past #24.", impostors: ["Invent a believable but false childhood memory #24.", "Make up a traumatic event from your youth #24.", "Describe a movie character's backstory without naming them #24."] },
  { real: "Describe a meaningful life memory from your past #25.", impostors: ["Invent a believable but false childhood memory #25.", "Make up a traumatic event from your youth #25.", "Describe a movie character's backstory without naming them #25."] },
  { real: "Describe a meaningful life memory from your past #26.", impostors: ["Invent a believable but false childhood memory #26.", "Make up a traumatic event from your youth #26.", "Describe a movie character's backstory without naming them #26."] },
  { real: "Describe a meaningful life memory from your past #27.", impostors: ["Invent a believable but false childhood memory #27.", "Make up a traumatic event from your youth #27.", "Describe a movie character's backstory without naming them #27."] },
  { real: "Describe a meaningful life memory from your past #28.", impostors: ["Invent a believable but false childhood memory #28.", "Make up a traumatic event from your youth #28.", "Describe a movie character's backstory without naming them #28."] },
  { real: "Describe a meaningful life memory from your past #29.", impostors: ["Invent a believable but false childhood memory #29.", "Make up a traumatic event from your youth #29.", "Describe a movie character's backstory without naming them #29."] },
  { real: "Describe a meaningful life memory from your past #30.", impostors: ["Invent a believable but false childhood memory #30.", "Make up a traumatic event from your youth #30.", "Describe a movie character's backstory without naming them #30."] },
  { real: "Describe a meaningful life memory from your past #31.", impostors: ["Invent a believable but false childhood memory #31.", "Make up a traumatic event from your youth #31.", "Describe a movie character's backstory without naming them #31."] },
  { real: "Describe a meaningful life memory from your past #32.", impostors: ["Invent a believable but false childhood memory #32.", "Make up a traumatic event from your youth #32.", "Describe a movie character's backstory without naming them #32."] },
  { real: "Describe a meaningful life memory from your past #33.", impostors: ["Invent a believable but false childhood memory #33.", "Make up a traumatic event from your youth #33.", "Describe a movie character's backstory without naming them #33."] },
  { real: "Describe a meaningful life memory from your past #34.", impostors: ["Invent a believable but false childhood memory #34.", "Make up a traumatic event from your youth #34.", "Describe a movie character's backstory without naming them #34."] },
  { real: "Describe a meaningful life memory from your past #35.", impostors: ["Invent a believable but false childhood memory #35.", "Make up a traumatic event from your youth #35.", "Describe a movie character's backstory without naming them #35."] },
  { real: "Describe a meaningful life memory from your past #36.", impostors: ["Invent a believable but false childhood memory #36.", "Make up a traumatic event from your youth #36.", "Describe a movie character's backstory without naming them #36."] },
  { real: "Describe a meaningful life memory from your past #37.", impostors: ["Invent a believable but false childhood memory #37.", "Make up a traumatic event from your youth #37.", "Describe a movie character's backstory without naming them #37."] },
  { real: "Describe a meaningful life memory from your past #38.", impostors: ["Invent a believable but false childhood memory #38.", "Make up a traumatic event from your youth #38.", "Describe a movie character's backstory without naming them #38."] },
  { real: "Describe a meaningful life memory from your past #39.", impostors: ["Invent a believable but false childhood memory #39.", "Make up a traumatic event from your youth #39.", "Describe a movie character's backstory without naming them #39."] },
  { real: "Describe a meaningful life memory from your past #40.", impostors: ["Invent a believable but false childhood memory #40.", "Make up a traumatic event from your youth #40.", "Describe a movie character's backstory without naming them #40."] },
  { real: "Describe a meaningful life memory from your past #41.", impostors: ["Invent a believable but false childhood memory #41.", "Make up a traumatic event from your youth #41.", "Describe a movie character's backstory without naming them #41."] },
  { real: "Describe a meaningful life memory from your past #42.", impostors: ["Invent a believable but false childhood memory #42.", "Make up a traumatic event from your youth #42.", "Describe a movie character's backstory without naming them #42."] },
  { real: "Describe a meaningful life memory from your past #43.", impostors: ["Invent a believable but false childhood memory #43.", "Make up a traumatic event from your youth #43.", "Describe a movie character's backstory without naming them #43."] },
  { real: "Describe a meaningful life memory from your past #44.", impostors: ["Invent a believable but false childhood memory #44.", "Make up a traumatic event from your youth #44.", "Describe a movie character's backstory without naming them #44."] },
  { real: "Describe a meaningful life memory from your past #45.", impostors: ["Invent a believable but false childhood memory #45.", "Make up a traumatic event from your youth #45.", "Describe a movie character's backstory without naming them #45."] },
  { real: "Describe a meaningful life memory from your past #46.", impostors: ["Invent a believable but false childhood memory #46.", "Make up a traumatic event from your youth #46.", "Describe a movie character's backstory without naming them #46."] },
  { real: "Describe a meaningful life memory from your past #47.", impostors: ["Invent a believable but false childhood memory #47.", "Make up a traumatic event from your youth #47.", "Describe a movie character's backstory without naming them #47."] },
  { real: "Describe a meaningful life memory from your past #48.", impostors: ["Invent a believable but false childhood memory #48.", "Make up a traumatic event from your youth #48.", "Describe a movie character's backstory without naming them #48."] },
  { real: "Describe a meaningful life memory from your past #49.", impostors: ["Invent a believable but false childhood memory #49.", "Make up a traumatic event from your youth #49.", "Describe a movie character's backstory without naming them #49."] },
  { real: "Describe a meaningful life memory from your past #50.", impostors: ["Invent a believable but false childhood memory #50.", "Make up a traumatic event from your youth #50.", "Describe a movie character's backstory without naming them #50."] },
  { real: "Describe a meaningful life memory from your past #51.", impostors: ["Invent a believable but false childhood memory #51.", "Make up a traumatic event from your youth #51.", "Describe a movie character's backstory without naming them #51."] },
  { real: "Describe a meaningful life memory from your past #52.", impostors: ["Invent a believable but false childhood memory #52.", "Make up a traumatic event from your youth #52.", "Describe a movie character's backstory without naming them #52."] },
  { real: "Describe a meaningful life memory from your past #53.", impostors: ["Invent a believable but false childhood memory #53.", "Make up a traumatic event from your youth #53.", "Describe a movie character's backstory without naming them #53."] },
  { real: "Describe a meaningful life memory from your past #54.", impostors: ["Invent a believable but false childhood memory #54.", "Make up a traumatic event from your youth #54.", "Describe a movie character's backstory without naming them #54."] },
  { real: "Describe a meaningful life memory from your past #55.", impostors: ["Invent a believable but false childhood memory #55.", "Make up a traumatic event from your youth #55.", "Describe a movie character's backstory without naming them #55."] },
  { real: "Describe a meaningful life memory from your past #56.", impostors: ["Invent a believable but false childhood memory #56.", "Make up a traumatic event from your youth #56.", "Describe a movie character's backstory without naming them #56."] },
  { real: "Describe a meaningful life memory from your past #57.", impostors: ["Invent a believable but false childhood memory #57.", "Make up a traumatic event from your youth #57.", "Describe a movie character's backstory without naming them #57."] },
  { real: "Describe a meaningful life memory from your past #58.", impostors: ["Invent a believable but false childhood memory #58.", "Make up a traumatic event from your youth #58.", "Describe a movie character's backstory without naming them #58."] },
  { real: "Describe a meaningful life memory from your past #59.", impostors: ["Invent a believable but false childhood memory #59.", "Make up a traumatic event from your youth #59.", "Describe a movie character's backstory without naming them #59."] },
  { real: "Describe a meaningful life memory from your past #60.", impostors: ["Invent a believable but false childhood memory #60.", "Make up a traumatic event from your youth #60.", "Describe a movie character's backstory without naming them #60."] },
  { real: "Describe a meaningful life memory from your past #61.", impostors: ["Invent a believable but false childhood memory #61.", "Make up a traumatic event from your youth #61.", "Describe a movie character's backstory without naming them #61."] },
  { real: "Describe a meaningful life memory from your past #62.", impostors: ["Invent a believable but false childhood memory #62.", "Make up a traumatic event from your youth #62.", "Describe a movie character's backstory without naming them #62."] },
  { real: "Describe a meaningful life memory from your past #63.", impostors: ["Invent a believable but false childhood memory #63.", "Make up a traumatic event from your youth #63.", "Describe a movie character's backstory without naming them #63."] },
  { real: "Describe a meaningful life memory from your past #64.", impostors: ["Invent a believable but false childhood memory #64.", "Make up a traumatic event from your youth #64.", "Describe a movie character's backstory without naming them #64."] },
  { real: "Describe a meaningful life memory from your past #65.", impostors: ["Invent a believable but false childhood memory #65.", "Make up a traumatic event from your youth #65.", "Describe a movie character's backstory without naming them #65."] },
  { real: "Describe a meaningful life memory from your past #66.", impostors: ["Invent a believable but false childhood memory #66.", "Make up a traumatic event from your youth #66.", "Describe a movie character's backstory without naming them #66."] },
  { real: "Describe a meaningful life memory from your past #67.", impostors: ["Invent a believable but false childhood memory #67.", "Make up a traumatic event from your youth #67.", "Describe a movie character's backstory without naming them #67."] },
  { real: "Describe a meaningful life memory from your past #68.", impostors: ["Invent a believable but false childhood memory #68.", "Make up a traumatic event from your youth #68.", "Describe a movie character's backstory without naming them #68."] },
  { real: "Describe a meaningful life memory from your past #69.", impostors: ["Invent a believable but false childhood memory #69.", "Make up a traumatic event from your youth #69.", "Describe a movie character's backstory without naming them #69."] },
  { real: "Describe a meaningful life memory from your past #70.", impostors: ["Invent a believable but false childhood memory #70.", "Make up a traumatic event from your youth #70.", "Describe a movie character's backstory without naming them #70."] },
  { real: "Describe a meaningful life memory from your past #71.", impostors: ["Invent a believable but false childhood memory #71.", "Make up a traumatic event from your youth #71.", "Describe a movie character's backstory without naming them #71."] },
  { real: "Describe a meaningful life memory from your past #72.", impostors: ["Invent a believable but false childhood memory #72.", "Make up a traumatic event from your youth #72.", "Describe a movie character's backstory without naming them #72."] },
  { real: "Describe a meaningful life memory from your past #73.", impostors: ["Invent a believable but false childhood memory #73.", "Make up a traumatic event from your youth #73.", "Describe a movie character's backstory without naming them #73."] },
  { real: "Describe a meaningful life memory from your past #74.", impostors: ["Invent a believable but false childhood memory #74.", "Make up a traumatic event from your youth #74.", "Describe a movie character's backstory without naming them #74."] },
  { real: "Describe a meaningful life memory from your past #75.", impostors: ["Invent a believable but false childhood memory #75.", "Make up a traumatic event from your youth #75.", "Describe a movie character's backstory without naming them #75."] },
  { real: "Describe a meaningful life memory from your past #76.", impostors: ["Invent a believable but false childhood memory #76.", "Make up a traumatic event from your youth #76.", "Describe a movie character's backstory without naming them #76."] },
  { real: "Describe a meaningful life memory from your past #77.", impostors: ["Invent a believable but false childhood memory #77.", "Make up a traumatic event from your youth #77.", "Describe a movie character's backstory without naming them #77."] },
  { real: "Describe a meaningful life memory from your past #78.", impostors: ["Invent a believable but false childhood memory #78.", "Make up a traumatic event from your youth #78.", "Describe a movie character's backstory without naming them #78."] },
  { real: "Describe a meaningful life memory from your past #79.", impostors: ["Invent a believable but false childhood memory #79.", "Make up a traumatic event from your youth #79.", "Describe a movie character's backstory without naming them #79."] },
  { real: "Describe a meaningful life memory from your past #80.", impostors: ["Invent a believable but false childhood memory #80.", "Make up a traumatic event from your youth #80.", "Describe a movie character's backstory without naming them #80."] },
  { real: "Describe a meaningful life memory from your past #81.", impostors: ["Invent a believable but false childhood memory #81.", "Make up a traumatic event from your youth #81.", "Describe a movie character's backstory without naming them #81."] },
  { real: "Describe a meaningful life memory from your past #82.", impostors: ["Invent a believable but false childhood memory #82.", "Make up a traumatic event from your youth #82.", "Describe a movie character's backstory without naming them #82."] },
  { real: "Describe a meaningful life memory from your past #83.", impostors: ["Invent a believable but false childhood memory #83.", "Make up a traumatic event from your youth #83.", "Describe a movie character's backstory without naming them #83."] },
  { real: "Describe a meaningful life memory from your past #84.", impostors: ["Invent a believable but false childhood memory #84.", "Make up a traumatic event from your youth #84.", "Describe a movie character's backstory without naming them #84."] },
  { real: "Describe a meaningful life memory from your past #85.", impostors: ["Invent a believable but false childhood memory #85.", "Make up a traumatic event from your youth #85.", "Describe a movie character's backstory without naming them #85."] },
  { real: "Describe a meaningful life memory from your past #86.", impostors: ["Invent a believable but false childhood memory #86.", "Make up a traumatic event from your youth #86.", "Describe a movie character's backstory without naming them #86."] },
  { real: "Describe a meaningful life memory from your past #87.", impostors: ["Invent a believable but false childhood memory #87.", "Make up a traumatic event from your youth #87.", "Describe a movie character's backstory without naming them #87."] },
  { real: "Describe a meaningful life memory from your past #88.", impostors: ["Invent a believable but false childhood memory #88.", "Make up a traumatic event from your youth #88.", "Describe a movie character's backstory without naming them #88."] },
  { real: "Describe a meaningful life memory from your past #89.", impostors: ["Invent a believable but false childhood memory #89.", "Make up a traumatic event from your youth #89.", "Describe a movie character's backstory without naming them #89."] },
  { real: "Describe a meaningful life memory from your past #90.", impostors: ["Invent a believable but false childhood memory #90.", "Make up a traumatic event from your youth #90.", "Describe a movie character's backstory without naming them #90."] },
  { real: "Describe a meaningful life memory from your past #91.", impostors: ["Invent a believable but false childhood memory #91.", "Make up a traumatic event from your youth #91.", "Describe a movie character's backstory without naming them #91."] },
  { real: "Describe a meaningful life memory from your past #92.", impostors: ["Invent a believable but false childhood memory #92.", "Make up a traumatic event from your youth #92.", "Describe a movie character's backstory without naming them #92."] },
  { real: "Describe a meaningful life memory from your past #93.", impostors: ["Invent a believable but false childhood memory #93.", "Make up a traumatic event from your youth #93.", "Describe a movie character's backstory without naming them #93."] },
  { real: "Describe a meaningful life memory from your past #94.", impostors: ["Invent a believable but false childhood memory #94.", "Make up a traumatic event from your youth #94.", "Describe a movie character's backstory without naming them #94."] },
  { real: "Describe a meaningful life memory from your past #95.", impostors: ["Invent a believable but false childhood memory #95.", "Make up a traumatic event from your youth #95.", "Describe a movie character's backstory without naming them #95."] },
  { real: "Describe a meaningful life memory from your past #96.", impostors: ["Invent a believable but false childhood memory #96.", "Make up a traumatic event from your youth #96.", "Describe a movie character's backstory without naming them #96."] },
  { real: "Describe a meaningful life memory from your past #97.", impostors: ["Invent a believable but false childhood memory #97.", "Make up a traumatic event from your youth #97.", "Describe a movie character's backstory without naming them #97."] },
  { real: "Describe a meaningful life memory from your past #98.", impostors: ["Invent a believable but false childhood memory #98.", "Make up a traumatic event from your youth #98.", "Describe a movie character's backstory without naming them #98."] },
  { real: "Describe a meaningful life memory from your past #99.", impostors: ["Invent a believable but false childhood memory #99.", "Make up a traumatic event from your youth #99.", "Describe a movie character's backstory without naming them #99."] },
  { real: "Describe a meaningful life memory from your past #100.", impostors: ["Invent a believable but false childhood memory #100.", "Make up a traumatic event from your youth #100.", "Describe a movie character's backstory without naming them #100."] },
  { real: "Describe a meaningful life memory from your past #101.", impostors: ["Invent a believable but false childhood memory #101.", "Make up a traumatic event from your youth #101.", "Describe a movie character's backstory without naming them #101."] },
  { real: "Describe a meaningful life memory from your past #102.", impostors: ["Invent a believable but false childhood memory #102.", "Make up a traumatic event from your youth #102.", "Describe a movie character's backstory without naming them #102."] },
  { real: "Describe a meaningful life memory from your past #103.", impostors: ["Invent a believable but false childhood memory #103.", "Make up a traumatic event from your youth #103.", "Describe a movie character's backstory without naming them #103."] },
  { real: "Describe a meaningful life memory from your past #104.", impostors: ["Invent a believable but false childhood memory #104.", "Make up a traumatic event from your youth #104.", "Describe a movie character's backstory without naming them #104."] },
  { real: "Describe a meaningful life memory from your past #105.", impostors: ["Invent a believable but false childhood memory #105.", "Make up a traumatic event from your youth #105.", "Describe a movie character's backstory without naming them #105."] },
  { real: "Describe a meaningful life memory from your past #106.", impostors: ["Invent a believable but false childhood memory #106.", "Make up a traumatic event from your youth #106.", "Describe a movie character's backstory without naming them #106."] },
  { real: "Describe a meaningful life memory from your past #107.", impostors: ["Invent a believable but false childhood memory #107.", "Make up a traumatic event from your youth #107.", "Describe a movie character's backstory without naming them #107."] },
  { real: "Describe a meaningful life memory from your past #108.", impostors: ["Invent a believable but false childhood memory #108.", "Make up a traumatic event from your youth #108.", "Describe a movie character's backstory without naming them #108."] },
  { real: "Describe a meaningful life memory from your past #109.", impostors: ["Invent a believable but false childhood memory #109.", "Make up a traumatic event from your youth #109.", "Describe a movie character's backstory without naming them #109."] },
  { real: "Describe a meaningful life memory from your past #110.", impostors: ["Invent a believable but false childhood memory #110.", "Make up a traumatic event from your youth #110.", "Describe a movie character's backstory without naming them #110."] },
  { real: "Describe a meaningful life memory from your past #111.", impostors: ["Invent a believable but false childhood memory #111.", "Make up a traumatic event from your youth #111.", "Describe a movie character's backstory without naming them #111."] },
  { real: "Describe a meaningful life memory from your past #112.", impostors: ["Invent a believable but false childhood memory #112.", "Make up a traumatic event from your youth #112.", "Describe a movie character's backstory without naming them #112."] },
  { real: "Describe a meaningful life memory from your past #113.", impostors: ["Invent a believable but false childhood memory #113.", "Make up a traumatic event from your youth #113.", "Describe a movie character's backstory without naming them #113."] },
  { real: "Describe a meaningful life memory from your past #114.", impostors: ["Invent a believable but false childhood memory #114.", "Make up a traumatic event from your youth #114.", "Describe a movie character's backstory without naming them #114."] },
  { real: "Describe a meaningful life memory from your past #115.", impostors: ["Invent a believable but false childhood memory #115.", "Make up a traumatic event from your youth #115.", "Describe a movie character's backstory without naming them #115."] },
  { real: "Describe a meaningful life memory from your past #116.", impostors: ["Invent a believable but false childhood memory #116.", "Make up a traumatic event from your youth #116.", "Describe a movie character's backstory without naming them #116."] },
  { real: "Describe a meaningful life memory from your past #117.", impostors: ["Invent a believable but false childhood memory #117.", "Make up a traumatic event from your youth #117.", "Describe a movie character's backstory without naming them #117."] },
  { real: "Describe a meaningful life memory from your past #118.", impostors: ["Invent a believable but false childhood memory #118.", "Make up a traumatic event from your youth #118.", "Describe a movie character's backstory without naming them #118."] },
  { real: "Describe a meaningful life memory from your past #119.", impostors: ["Invent a believable but false childhood memory #119.", "Make up a traumatic event from your youth #119.", "Describe a movie character's backstory without naming them #119."] },
  { real: "Describe a meaningful life memory from your past #120.", impostors: ["Invent a believable but false childhood memory #120.", "Make up a traumatic event from your youth #120.", "Describe a movie character's backstory without naming them #120."] },
  { real: "Describe a meaningful life memory from your past #121.", impostors: ["Invent a believable but false childhood memory #121.", "Make up a traumatic event from your youth #121.", "Describe a movie character's backstory without naming them #121."] },
  { real: "Describe a meaningful life memory from your past #122.", impostors: ["Invent a believable but false childhood memory #122.", "Make up a traumatic event from your youth #122.", "Describe a movie character's backstory without naming them #122."] },
  { real: "Describe a meaningful life memory from your past #123.", impostors: ["Invent a believable but false childhood memory #123.", "Make up a traumatic event from your youth #123.", "Describe a movie character's backstory without naming them #123."] },
  { real: "Describe a meaningful life memory from your past #124.", impostors: ["Invent a believable but false childhood memory #124.", "Make up a traumatic event from your youth #124.", "Describe a movie character's backstory without naming them #124."] },
  { real: "Describe a meaningful life memory from your past #125.", impostors: ["Invent a believable but false childhood memory #125.", "Make up a traumatic event from your youth #125.", "Describe a movie character's backstory without naming them #125."] },
  { real: "Describe a meaningful life memory from your past #126.", impostors: ["Invent a believable but false childhood memory #126.", "Make up a traumatic event from your youth #126.", "Describe a movie character's backstory without naming them #126."] },
  { real: "Describe a meaningful life memory from your past #127.", impostors: ["Invent a believable but false childhood memory #127.", "Make up a traumatic event from your youth #127.", "Describe a movie character's backstory without naming them #127."] },
  { real: "Describe a meaningful life memory from your past #128.", impostors: ["Invent a believable but false childhood memory #128.", "Make up a traumatic event from your youth #128.", "Describe a movie character's backstory without naming them #128."] },
  { real: "Describe a meaningful life memory from your past #129.", impostors: ["Invent a believable but false childhood memory #129.", "Make up a traumatic event from your youth #129.", "Describe a movie character's backstory without naming them #129."] },
  { real: "Describe a meaningful life memory from your past #130.", impostors: ["Invent a believable but false childhood memory #130.", "Make up a traumatic event from your youth #130.", "Describe a movie character's backstory without naming them #130."] },
  { real: "Describe a meaningful life memory from your past #131.", impostors: ["Invent a believable but false childhood memory #131.", "Make up a traumatic event from your youth #131.", "Describe a movie character's backstory without naming them #131."] },
  { real: "Describe a meaningful life memory from your past #132.", impostors: ["Invent a believable but false childhood memory #132.", "Make up a traumatic event from your youth #132.", "Describe a movie character's backstory without naming them #132."] },
  { real: "Describe a meaningful life memory from your past #133.", impostors: ["Invent a believable but false childhood memory #133.", "Make up a traumatic event from your youth #133.", "Describe a movie character's backstory without naming them #133."] },
  { real: "Describe a meaningful life memory from your past #134.", impostors: ["Invent a believable but false childhood memory #134.", "Make up a traumatic event from your youth #134.", "Describe a movie character's backstory without naming them #134."] },
  { real: "Describe a meaningful life memory from your past #135.", impostors: ["Invent a believable but false childhood memory #135.", "Make up a traumatic event from your youth #135.", "Describe a movie character's backstory without naming them #135."] },
  { real: "Describe a meaningful life memory from your past #136.", impostors: ["Invent a believable but false childhood memory #136.", "Make up a traumatic event from your youth #136.", "Describe a movie character's backstory without naming them #136."] },
  { real: "Describe a meaningful life memory from your past #137.", impostors: ["Invent a believable but false childhood memory #137.", "Make up a traumatic event from your youth #137.", "Describe a movie character's backstory without naming them #137."] },
  { real: "Describe a meaningful life memory from your past #138.", impostors: ["Invent a believable but false childhood memory #138.", "Make up a traumatic event from your youth #138.", "Describe a movie character's backstory without naming them #138."] },
  { real: "Describe a meaningful life memory from your past #139.", impostors: ["Invent a believable but false childhood memory #139.", "Make up a traumatic event from your youth #139.", "Describe a movie character's backstory without naming them #139."] },
  { real: "Describe a meaningful life memory from your past #140.", impostors: ["Invent a believable but false childhood memory #140.", "Make up a traumatic event from your youth #140.", "Describe a movie character's backstory without naming them #140."] },
  { real: "Describe a meaningful life memory from your past #141.", impostors: ["Invent a believable but false childhood memory #141.", "Make up a traumatic event from your youth #141.", "Describe a movie character's backstory without naming them #141."] },
  { real: "Describe a meaningful life memory from your past #142.", impostors: ["Invent a believable but false childhood memory #142.", "Make up a traumatic event from your youth #142.", "Describe a movie character's backstory without naming them #142."] },
  { real: "Describe a meaningful life memory from your past #143.", impostors: ["Invent a believable but false childhood memory #143.", "Make up a traumatic event from your youth #143.", "Describe a movie character's backstory without naming them #143."] },
  { real: "Describe a meaningful life memory from your past #144.", impostors: ["Invent a believable but false childhood memory #144.", "Make up a traumatic event from your youth #144.", "Describe a movie character's backstory without naming them #144."] },
  { real: "Describe a meaningful life memory from your past #145.", impostors: ["Invent a believable but false childhood memory #145.", "Make up a traumatic event from your youth #145.", "Describe a movie character's backstory without naming them #145."] },
  { real: "Describe a meaningful life memory from your past #146.", impostors: ["Invent a believable but false childhood memory #146.", "Make up a traumatic event from your youth #146.", "Describe a movie character's backstory without naming them #146."] },
  { real: "Describe a meaningful life memory from your past #147.", impostors: ["Invent a believable but false childhood memory #147.", "Make up a traumatic event from your youth #147.", "Describe a movie character's backstory without naming them #147."] },
  { real: "Describe a meaningful life memory from your past #148.", impostors: ["Invent a believable but false childhood memory #148.", "Make up a traumatic event from your youth #148.", "Describe a movie character's backstory without naming them #148."] },
  { real: "Describe a meaningful life memory from your past #149.", impostors: ["Invent a believable but false childhood memory #149.", "Make up a traumatic event from your youth #149.", "Describe a movie character's backstory without naming them #149."] },
  { real: "Describe a meaningful life memory from your past #150.", impostors: ["Invent a believable but false childhood memory #150.", "Make up a traumatic event from your youth #150.", "Describe a movie character's backstory without naming them #150."] },
  { real: "Describe a meaningful life memory from your past #151.", impostors: ["Invent a believable but false childhood memory #151.", "Make up a traumatic event from your youth #151.", "Describe a movie character's backstory without naming them #151."] },
  { real: "Describe a meaningful life memory from your past #152.", impostors: ["Invent a believable but false childhood memory #152.", "Make up a traumatic event from your youth #152.", "Describe a movie character's backstory without naming them #152."] },
  { real: "Describe a meaningful life memory from your past #153.", impostors: ["Invent a believable but false childhood memory #153.", "Make up a traumatic event from your youth #153.", "Describe a movie character's backstory without naming them #153."] },
  { real: "Describe a meaningful life memory from your past #154.", impostors: ["Invent a believable but false childhood memory #154.", "Make up a traumatic event from your youth #154.", "Describe a movie character's backstory without naming them #154."] },
  { real: "Describe a meaningful life memory from your past #155.", impostors: ["Invent a believable but false childhood memory #155.", "Make up a traumatic event from your youth #155.", "Describe a movie character's backstory without naming them #155."] },
  { real: "Describe a meaningful life memory from your past #156.", impostors: ["Invent a believable but false childhood memory #156.", "Make up a traumatic event from your youth #156.", "Describe a movie character's backstory without naming them #156."] },
  { real: "Describe a meaningful life memory from your past #157.", impostors: ["Invent a believable but false childhood memory #157.", "Make up a traumatic event from your youth #157.", "Describe a movie character's backstory without naming them #157."] },
  { real: "Describe a meaningful life memory from your past #158.", impostors: ["Invent a believable but false childhood memory #158.", "Make up a traumatic event from your youth #158.", "Describe a movie character's backstory without naming them #158."] },
  { real: "Describe a meaningful life memory from your past #159.", impostors: ["Invent a believable but false childhood memory #159.", "Make up a traumatic event from your youth #159.", "Describe a movie character's backstory without naming them #159."] },
  { real: "Describe a meaningful life memory from your past #160.", impostors: ["Invent a believable but false childhood memory #160.", "Make up a traumatic event from your youth #160.", "Describe a movie character's backstory without naming them #160."] },
  { real: "Describe a meaningful life memory from your past #161.", impostors: ["Invent a believable but false childhood memory #161.", "Make up a traumatic event from your youth #161.", "Describe a movie character's backstory without naming them #161."] },
  { real: "Describe a meaningful life memory from your past #162.", impostors: ["Invent a believable but false childhood memory #162.", "Make up a traumatic event from your youth #162.", "Describe a movie character's backstory without naming them #162."] },
  { real: "Describe a meaningful life memory from your past #163.", impostors: ["Invent a believable but false childhood memory #163.", "Make up a traumatic event from your youth #163.", "Describe a movie character's backstory without naming them #163."] },
  { real: "Describe a meaningful life memory from your past #164.", impostors: ["Invent a believable but false childhood memory #164.", "Make up a traumatic event from your youth #164.", "Describe a movie character's backstory without naming them #164."] },
  { real: "Describe a meaningful life memory from your past #165.", impostors: ["Invent a believable but false childhood memory #165.", "Make up a traumatic event from your youth #165.", "Describe a movie character's backstory without naming them #165."] },
  { real: "Describe a meaningful life memory from your past #166.", impostors: ["Invent a believable but false childhood memory #166.", "Make up a traumatic event from your youth #166.", "Describe a movie character's backstory without naming them #166."] },
  { real: "Describe a meaningful life memory from your past #167.", impostors: ["Invent a believable but false childhood memory #167.", "Make up a traumatic event from your youth #167.", "Describe a movie character's backstory without naming them #167."] },
  { real: "Describe a meaningful life memory from your past #168.", impostors: ["Invent a believable but false childhood memory #168.", "Make up a traumatic event from your youth #168.", "Describe a movie character's backstory without naming them #168."] },
  { real: "Describe a meaningful life memory from your past #169.", impostors: ["Invent a believable but false childhood memory #169.", "Make up a traumatic event from your youth #169.", "Describe a movie character's backstory without naming them #169."] },
  { real: "Describe a meaningful life memory from your past #170.", impostors: ["Invent a believable but false childhood memory #170.", "Make up a traumatic event from your youth #170.", "Describe a movie character's backstory without naming them #170."] },
  { real: "Describe a meaningful life memory from your past #171.", impostors: ["Invent a believable but false childhood memory #171.", "Make up a traumatic event from your youth #171.", "Describe a movie character's backstory without naming them #171."] },
  { real: "Describe a meaningful life memory from your past #172.", impostors: ["Invent a believable but false childhood memory #172.", "Make up a traumatic event from your youth #172.", "Describe a movie character's backstory without naming them #172."] },
  { real: "Describe a meaningful life memory from your past #173.", impostors: ["Invent a believable but false childhood memory #173.", "Make up a traumatic event from your youth #173.", "Describe a movie character's backstory without naming them #173."] },
  { real: "Describe a meaningful life memory from your past #174.", impostors: ["Invent a believable but false childhood memory #174.", "Make up a traumatic event from your youth #174.", "Describe a movie character's backstory without naming them #174."] },
  { real: "Describe a meaningful life memory from your past #175.", impostors: ["Invent a believable but false childhood memory #175.", "Make up a traumatic event from your youth #175.", "Describe a movie character's backstory without naming them #175."] },
  { real: "Describe a meaningful life memory from your past #176.", impostors: ["Invent a believable but false childhood memory #176.", "Make up a traumatic event from your youth #176.", "Describe a movie character's backstory without naming them #176."] },
  { real: "Describe a meaningful life memory from your past #177.", impostors: ["Invent a believable but false childhood memory #177.", "Make up a traumatic event from your youth #177.", "Describe a movie character's backstory without naming them #177."] },
  { real: "Describe a meaningful life memory from your past #178.", impostors: ["Invent a believable but false childhood memory #178.", "Make up a traumatic event from your youth #178.", "Describe a movie character's backstory without naming them #178."] },
  { real: "Describe a meaningful life memory from your past #179.", impostors: ["Invent a believable but false childhood memory #179.", "Make up a traumatic event from your youth #179.", "Describe a movie character's backstory without naming them #179."] },
  { real: "Describe a meaningful life memory from your past #180.", impostors: ["Invent a believable but false childhood memory #180.", "Make up a traumatic event from your youth #180.", "Describe a movie character's backstory without naming them #180."] },
  { real: "Describe a meaningful life memory from your past #181.", impostors: ["Invent a believable but false childhood memory #181.", "Make up a traumatic event from your youth #181.", "Describe a movie character's backstory without naming them #181."] },
  { real: "Describe a meaningful life memory from your past #182.", impostors: ["Invent a believable but false childhood memory #182.", "Make up a traumatic event from your youth #182.", "Describe a movie character's backstory without naming them #182."] },
  { real: "Describe a meaningful life memory from your past #183.", impostors: ["Invent a believable but false childhood memory #183.", "Make up a traumatic event from your youth #183.", "Describe a movie character's backstory without naming them #183."] },
  { real: "Describe a meaningful life memory from your past #184.", impostors: ["Invent a believable but false childhood memory #184.", "Make up a traumatic event from your youth #184.", "Describe a movie character's backstory without naming them #184."] },
  { real: "Describe a meaningful life memory from your past #185.", impostors: ["Invent a believable but false childhood memory #185.", "Make up a traumatic event from your youth #185.", "Describe a movie character's backstory without naming them #185."] },
  { real: "Describe a meaningful life memory from your past #186.", impostors: ["Invent a believable but false childhood memory #186.", "Make up a traumatic event from your youth #186.", "Describe a movie character's backstory without naming them #186."] },
  { real: "Describe a meaningful life memory from your past #187.", impostors: ["Invent a believable but false childhood memory #187.", "Make up a traumatic event from your youth #187.", "Describe a movie character's backstory without naming them #187."] },
  { real: "Describe a meaningful life memory from your past #188.", impostors: ["Invent a believable but false childhood memory #188.", "Make up a traumatic event from your youth #188.", "Describe a movie character's backstory without naming them #188."] },
  { real: "Describe a meaningful life memory from your past #189.", impostors: ["Invent a believable but false childhood memory #189.", "Make up a traumatic event from your youth #189.", "Describe a movie character's backstory without naming them #189."] },
  { real: "Describe a meaningful life memory from your past #190.", impostors: ["Invent a believable but false childhood memory #190.", "Make up a traumatic event from your youth #190.", "Describe a movie character's backstory without naming them #190."] },
  { real: "Describe a meaningful life memory from your past #191.", impostors: ["Invent a believable but false childhood memory #191.", "Make up a traumatic event from your youth #191.", "Describe a movie character's backstory without naming them #191."] },
  { real: "Describe a meaningful life memory from your past #192.", impostors: ["Invent a believable but false childhood memory #192.", "Make up a traumatic event from your youth #192.", "Describe a movie character's backstory without naming them #192."] },
  { real: "Describe a meaningful life memory from your past #193.", impostors: ["Invent a believable but false childhood memory #193.", "Make up a traumatic event from your youth #193.", "Describe a movie character's backstory without naming them #193."] },
  { real: "Describe a meaningful life memory from your past #194.", impostors: ["Invent a believable but false childhood memory #194.", "Make up a traumatic event from your youth #194.", "Describe a movie character's backstory without naming them #194."] },
  { real: "Describe a meaningful life memory from your past #195.", impostors: ["Invent a believable but false childhood memory #195.", "Make up a traumatic event from your youth #195.", "Describe a movie character's backstory without naming them #195."] },
  { real: "Describe a meaningful life memory from your past #196.", impostors: ["Invent a believable but false childhood memory #196.", "Make up a traumatic event from your youth #196.", "Describe a movie character's backstory without naming them #196."] },
  { real: "Describe a meaningful life memory from your past #197.", impostors: ["Invent a believable but false childhood memory #197.", "Make up a traumatic event from your youth #197.", "Describe a movie character's backstory without naming them #197."] },
  { real: "Describe a meaningful life memory from your past #198.", impostors: ["Invent a believable but false childhood memory #198.", "Make up a traumatic event from your youth #198.", "Describe a movie character's backstory without naming them #198."] },
  { real: "Describe a meaningful life memory from your past #199.", impostors: ["Invent a believable but false childhood memory #199.", "Make up a traumatic event from your youth #199.", "Describe a movie character's backstory without naming them #199."] },
  { real: "Describe a meaningful life memory from your past #200.", impostors: ["Invent a believable but false childhood memory #200.", "Make up a traumatic event from your youth #200.", "Describe a movie character's backstory without naming them #200."] }
];

// -------------------------------
// ITEMS (300)
// -------------------------------
const ITEMS = [
  "FamousThing_1",
  "FamousThing_2",
  "FamousThing_3",
  "FamousThing_4",
  "FamousThing_5",
  "FamousThing_6",
  "FamousThing_7",
  "FamousThing_8",
  "FamousThing_9",
  "FamousThing_10",
  "FamousThing_11",
  "FamousThing_12",
  "FamousThing_13",
  "FamousThing_14",
  "FamousThing_15",
  "FamousThing_16",
  "FamousThing_17",
  "FamousThing_18",
  "FamousThing_19",
  "FamousThing_20",
  "FamousThing_21",
  "FamousThing_22",
  "FamousThing_23",
  "FamousThing_24",
  "FamousThing_25",
  "FamousThing_26",
  "FamousThing_27",
  "FamousThing_28",
  "FamousThing_29",
  "FamousThing_30",
  "FamousThing_31",
  "FamousThing_32",
  "FamousThing_33",
  "FamousThing_34",
  "FamousThing_35",
  "FamousThing_36",
  "FamousThing_37",
  "FamousThing_38",
  "FamousThing_39",
  "FamousThing_40",
  "FamousThing_41",
  "FamousThing_42",
  "FamousThing_43",
  "FamousThing_44",
  "FamousThing_45",
  "FamousThing_46",
  "FamousThing_47",
  "FamousThing_48",
  "FamousThing_49",
  "FamousThing_50",
  "FamousThing_51",
  "FamousThing_52",
  "FamousThing_53",
  "FamousThing_54",
  "FamousThing_55",
  "FamousThing_56",
  "FamousThing_57",
  "FamousThing_58",
  "FamousThing_59",
  "FamousThing_60",
  "FamousThing_61",
  "FamousThing_62",
  "FamousThing_63",
  "FamousThing_64",
  "FamousThing_65",
  "FamousThing_66",
  "FamousThing_67",
  "FamousThing_68",
  "FamousThing_69",
  "FamousThing_70",
  "FamousThing_71",
  "FamousThing_72",
  "FamousThing_73",
  "FamousThing_74",
  "FamousThing_75",
  "FamousThing_76",
  "FamousThing_77",
  "FamousThing_78",
  "FamousThing_79",
  "FamousThing_80",
  "FamousThing_81",
  "FamousThing_82",
  "FamousThing_83",
  "FamousThing_84",
  "FamousThing_85",
  "FamousThing_86",
  "FamousThing_87",
  "FamousThing_88",
  "FamousThing_89",
  "FamousThing_90",
  "FamousThing_91",
  "FamousThing_92",
  "FamousThing_93",
  "FamousThing_94",
  "FamousThing_95",
  "FamousThing_96",
  "FamousThing_97",
  "FamousThing_98",
  "FamousThing_99",
  "FamousThing_100",
  "FamousThing_101",
  "FamousThing_102",
  "FamousThing_103",
  "FamousThing_104",
  "FamousThing_105",
  "FamousThing_106",
  "FamousThing_107",
  "FamousThing_108",
  "FamousThing_109",
  "FamousThing_110",
  "FamousThing_111",
  "FamousThing_112",
  "FamousThing_113",
  "FamousThing_114",
  "FamousThing_115",
  "FamousThing_116",
  "FamousThing_117",
  "FamousThing_118",
  "FamousThing_119",
  "FamousThing_120",
  "FamousThing_121",
  "FamousThing_122",
  "FamousThing_123",
  "FamousThing_124",
  "FamousThing_125",
  "FamousThing_126",
  "FamousThing_127",
  "FamousThing_128",
  "FamousThing_129",
  "FamousThing_130",
  "FamousThing_131",
  "FamousThing_132",
  "FamousThing_133",
  "FamousThing_134",
  "FamousThing_135",
  "FamousThing_136",
  "FamousThing_137",
  "FamousThing_138",
  "FamousThing_139",
  "FamousThing_140",
  "FamousThing_141",
  "FamousThing_142",
  "FamousThing_143",
  "FamousThing_144",
  "FamousThing_145",
  "FamousThing_146",
  "FamousThing_147",
  "FamousThing_148",
  "FamousThing_149",
  "FamousThing_150",
  "FamousThing_151",
  "FamousThing_152",
  "FamousThing_153",
  "FamousThing_154",
  "FamousThing_155",
  "FamousThing_156",
  "FamousThing_157",
  "FamousThing_158",
  "FamousThing_159",
  "FamousThing_160",
  "FamousThing_161",
  "FamousThing_162",
  "FamousThing_163",
  "FamousThing_164",
  "FamousThing_165",
  "FamousThing_166",
  "FamousThing_167",
  "FamousThing_168",
  "FamousThing_169",
  "FamousThing_170",
  "FamousThing_171",
  "FamousThing_172",
  "FamousThing_173",
  "FamousThing_174",
  "FamousThing_175",
  "FamousThing_176",
  "FamousThing_177",
  "FamousThing_178",
  "FamousThing_179",
  "FamousThing_180",
  "FamousThing_181",
  "FamousThing_182",
  "FamousThing_183",
  "FamousThing_184",
  "FamousThing_185",
  "FamousThing_186",
  "FamousThing_187",
  "FamousThing_188",
  "FamousThing_189",
  "FamousThing_190",
  "FamousThing_191",
  "FamousThing_192",
  "FamousThing_193",
  "FamousThing_194",
  "FamousThing_195",
  "FamousThing_196",
  "FamousThing_197",
  "FamousThing_198",
  "FamousThing_199",
  "FamousThing_200",
  "FamousThing_201",
  "FamousThing_202",
  "FamousThing_203",
  "FamousThing_204",
  "FamousThing_205",
  "FamousThing_206",
  "FamousThing_207",
  "FamousThing_208",
  "FamousThing_209",
  "FamousThing_210",
  "FamousThing_211",
  "FamousThing_212",
  "FamousThing_213",
  "FamousThing_214",
  "FamousThing_215",
  "FamousThing_216",
  "FamousThing_217",
  "FamousThing_218",
  "FamousThing_219",
  "FamousThing_220",
  "FamousThing_221",
  "FamousThing_222",
  "FamousThing_223",
  "FamousThing_224",
  "FamousThing_225",
  "FamousThing_226",
  "FamousThing_227",
  "FamousThing_228",
  "FamousThing_229",
  "FamousThing_230",
  "FamousThing_231",
  "FamousThing_232",
  "FamousThing_233",
  "FamousThing_234",
  "FamousThing_235",
  "FamousThing_236",
  "FamousThing_237",
  "FamousThing_238",
  "FamousThing_239",
  "FamousThing_240",
  "FamousThing_241",
  "FamousThing_242",
  "FamousThing_243",
  "FamousThing_244",
  "FamousThing_245",
  "FamousThing_246",
  "FamousThing_247",
  "FamousThing_248",
  "FamousThing_249",
  "FamousThing_250",
  "FamousThing_251",
  "FamousThing_252",
  "FamousThing_253",
  "FamousThing_254",
  "FamousThing_255",
  "FamousThing_256",
  "FamousThing_257",
  "FamousThing_258",
  "FamousThing_259",
  "FamousThing_260",
  "FamousThing_261",
  "FamousThing_262",
  "FamousThing_263",
  "FamousThing_264",
  "FamousThing_265",
  "FamousThing_266",
  "FamousThing_267",
  "FamousThing_268",
  "FamousThing_269",
  "FamousThing_270",
  "FamousThing_271",
  "FamousThing_272",
  "FamousThing_273",
  "FamousThing_274",
  "FamousThing_275",
  "FamousThing_276",
  "FamousThing_277",
  "FamousThing_278",
  "FamousThing_279",
  "FamousThing_280",
  "FamousThing_281",
  "FamousThing_282",
  "FamousThing_283",
  "FamousThing_284",
  "FamousThing_285",
  "FamousThing_286",
  "FamousThing_287",
  "FamousThing_288",
  "FamousThing_289",
  "FamousThing_290",
  "FamousThing_291",
  "FamousThing_292",
  "FamousThing_293",
  "FamousThing_294",
  "FamousThing_295",
  "FamousThing_296",
  "FamousThing_297",
  "FamousThing_298",
  "FamousThing_299",
  "FamousThing_300"
];

// -------------------------------
// Simple sound helper (click to enable in browser)
// -------------------------------
const playSound = (name) => {
  try {
    if(!window.__SOUND_ENABLED__) return;
    const id = "sfx-"+name;
    let el = document.getElementById(id);
    if(!el){
      el = document.createElement("audio");
      el.id = id;
      el.src = ""; // optional: supply URLs or base64
      document.body.appendChild(el);
    }
    el.play().catch(()=>{});
  } catch(e){}
};

// -------------------------------
// TRON styles injection
// -------------------------------
if(typeof document !== "undefined"){
  const css = `
  @import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&display=swap');
  body { background: #000814; color: #0ff; font-family: 'Orbitron', monospace; }
  .tron-panel { border: 2px solid #0ff; box-shadow: 0 0 12px #0ff inset, 0 0 18px rgba(0,255,255,0.06); padding: 12px; border-radius: 10px; margin: 8px 0; background: rgba(0,8,12,0.45); }
  .tron-btn { border: 2px solid #0ff; padding: 8px 12px; background: transparent; color: #0ff; border-radius: 8px; cursor: pointer; margin: 6px; }
  .avatar { width: 44px; height:44px; border-radius:50%; display:inline-flex; align-items:center; justify-content:center; font-size:20px; margin-right:8px; }
  .neon { text-shadow: 0 0 10px #0ff; }
  `;
  const s = document.createElement("style"); s.innerHTML = css; document.head.appendChild(s);
}

// -------------------------------
// Scoring function: +1 per correct guess, +2 to impostor if nobody guessed them
// -------------------------------
async function computeAndApplyScores(roomCode) {
  try{
    const roomRef = ref(db, "rooms/" + roomCode);
    const snap = await get(roomRef);
    if(!snap.exists()) return;
    const data = snap.val();
    const players = data.players || {};
    const impostors = data.impostors || [];
    const votesByPlayer = {};
    Object.entries(players).forEach(([p, info])=>{ votesByPlayer[p] = Array.isArray(info.vote) ? info.vote.slice() : []; });
    const newScores = {};
    Object.entries(players).forEach(([p, info])=>{ newScores[p] = Number(info.score||0) || 0; });
    const NO = NO_IMPOSTOR;
    // count guesses
    const guessedCount = {};
    Object.keys(players).forEach(p => guessedCount[p] = 0);
    Object.entries(votesByPlayer).forEach(([voter, list])=>{
      list.forEach(v => { if(v===NO) return; if(guessedCount[v]!==undefined) guessedCount[v]++; });
    });
    // reward voters
    Object.entries(votesByPlayer).forEach(([voter, list])=>{
      list.forEach(v => {
        if(v === NO) {
          // if no impostors exist, reward +1
          if(!impostors || impostors.length===0) newScores[voter] = (newScores[voter]||0) + 1;
        } else if(Array.isArray(impostors) && impostors.includes(v)) {
          newScores[voter] = (newScores[voter]||0) + 1;
        }
      });
    });
    // reward impostors if not guessed
    (impostors||[]).forEach(imp => {
      if(!guessedCount[imp] || guessedCount[imp]===0) newScores[imp] = (newScores[imp]||0) + 2;
    });
    // write back
    const updates = {};
    Object.entries(newScores).forEach(([p, s])=>{ updates["players/"+p+"/score"] = Number(s)||0; });
    await update(roomRef, updates);
  }catch(e){ console.error("score error", e); }
}

// -------------------------------
// Main App component
// -------------------------------
export default function App(){
  // user and room
  const [name, setName] = useState("");
  const [roomCode, setRoomCode] = useState("");
  const [creator, setCreator] = useState("");
  const [players, setPlayers] = useState({});
  const [phase, setPhase] = useState("lobby"); // lobby, answer, debate, vote, reveal, oneword_round, oneword_vote
  const [mode, setMode] = useState("liar"); // liar or oneword
  const [round, setRound] = useState(1);
  const [timerEnd, setTimerEnd] = useState(null);
  const [timeLeft, setTimeLeft] = useState(0);
  const [currentPrompt, setCurrentPrompt] = useState(null);
  const [currentItem, setCurrentItem] = useState(null);
  const [selectedVotes, setSelectedVotes] = useState([]);
  const [playerOrder, setPlayerOrder] = useState([]);
  const [turnIndex, setTurnIndex] = useState(0);
  const [oneWordClues, setOneWordClues] = useState({});
  const [confetti, setConfetti] = useState(null);

  // confetti lazy load
  useEffect(()=>{
    if(typeof window!=="undefined") import("canvas-confetti").then(m=>setConfetti(()=>m.default)).catch(()=>{});
  },[]);

  // listen to room
  useEffect(()=>{
    if(!roomCode) return;
    const r = ref(db, "rooms/" + roomCode);
    const unsub = onValue(r, snap=>{
      const d = snap.val() || {};
      setPlayers(d.players || {});
      setCreator(d.creator || "");
      setPhase(d.phase || "lobby");
      setMode(d.mode || "liar");
      setRound(d.round || 1);
      setTimerEnd(d.timerEnd || null);
      setCurrentPrompt(d.currentPrompt || null);
      setCurrentItem(d.currentItem || null);
      setPlayerOrder(d.playerOrder || []);
      setTurnIndex(d.currentTurnIndex || 0);
      setOneWordClues(d.oneWordClues || {});
    });
    return ()=>unsub();
  },[roomCode]);

  // timer tick & auto-advance
  useEffect(()=>{
    if(!timerEnd) { setTimeLeft(0); return; }
    const id = setInterval(async ()=>{
      const remain = Math.max(0, Math.ceil((timerEnd - Date.now())/1000));
      setTimeLeft(remain);
      if(remain===0){
        // phase auto-advance logic
        const r = ref(db, "rooms/" + roomCode);
        const snap = await get(r);
        if(!snap.exists()) return;
        const data = snap.val() || {};
        if(data.phase === "answer"){
          // go to debate
          await update(r, { phase: "debate", timerEnd: Date.now()+120000 });
        } else if(data.phase === "debate"){
          await update(r, { phase: "reveal", timerEnd: null });
        } else if(data.phase === "oneword_round"){
          await update(r, { phase: "oneword_vote", timerEnd: Date.now()+60000 });
        } else if(data.phase === "oneword_vote"){
          await update(r, { phase: "reveal", timerEnd: null });
        }
      }
    }, 1000);
    return ()=>clearInterval(id);
  },[timerEnd, roomCode]);

  // create room
  const createRoom = async ()=>{
    if(!name) return alert("Enter name");
    const code = String(Math.floor(Math.random()*9000+1000));
    const s = sanitize(code);
    const n = sanitize(name);
    setRoomCode(s);
    await set(ref(db, "rooms/" + s), {
      creator: n,
      players: { [n]: { avatar: randomItem(AVATARS), answer:"", vote:[], submitted:false, voteSubmitted:false, score:0 } },
      phase: "lobby",
      mode: "liar",
      round: 1,
      currentPrompt: null,
      currentItem: null,
      currentTurnIndex: 0,
      timerEnd: null,
      playerOrder: [],
      oneWordClues: {}
    });
  };

  // join room
  const joinRoom = async ()=>{
    if(!name || !roomCode) return alert("name+room needed");
    const s = sanitize(roomCode); const n = sanitize(name);
    const rRef = ref(db, "rooms/" + s);
    const snap = await get(rRef);
    if(!snap.exists()) return alert("Room not found");
    await set(ref(db, "rooms/" + s + "/players/" + n), { avatar: randomItem(AVATARS), answer:"", vote:[], submitted:false, voteSubmitted:false, score:0 });
  };

  // start liar round
  const startLiarRound = async ()=>{
    if(name !== creator) return alert("Only host");
    const s = sanitize(roomCode);
    const rRef = ref(db, "rooms/" + s);
    const snap = await get(rRef); if(!snap.exists()) return;
    const data = snap.val();
    const pnames = Object.keys(data.players || {});
    if(pnames.length < 2) return alert("Need ≥2 players");
    const prompt = randomItem(PROMPTS);
    const impCount = Math.floor(Math.random()*pnames.length); // 0..n-1
    const shuffled = shuffle(pnames);
    const impostors = shuffled.slice(0, impCount);
    const updated = {};
    pnames.forEach(p => {
      const isImp = impostors.includes(p);
      updated[p] = { ...data.players[p], answer:"", submitted:false, vote:[], voteSubmitted:false, variant: isImp ? randomItem(prompt.impostors) : prompt.real };
    });
    await update(rRef, { players: updated, impostors: impostors, currentPrompt: prompt.real, phase: "answer", timerEnd: Date.now()+60000, round: data.round||1 });
  };

  // start one-word round (random start)
  const startOneWordRound = async ()=>{
    if(name !== creator) return alert("Only host");
    const s = sanitize(roomCode);
    const rRef = ref(db, "rooms/" + s);
    const snap = await get(rRef); if(!snap.exists()) return;
    const data = snap.val();
    const pnames = Object.keys(data.players || {});
    if(pnames.length < 2) return alert("Need ≥2 players");
    const item = randomItem(ITEMS);
    const shuffled = shuffle(pnames);
    const rot = Math.floor(Math.random()*shuffled.length);
    const rotated = [...shuffled.slice(rot), ...shuffled.slice(0,rot)];
    const updated = {};
    pnames.forEach(p => updated[p] = { ...data.players[p], clue:"", clueSubmitted:false, vote:[], voteSubmitted:false });
    await update(rRef, { players: updated, phase: "oneword_round", currentItem: item, playerOrder: rotated, currentTurnIndex: 0, timerEnd: Date.now()+4*60*1000, oneWordClues: {}, round: data.round||1 });
  };

  // submit answer (liar)
  const submitAnswer = async (ans) => {
    if(!roomCode || !name) return;
    const s = sanitize(roomCode); const n = sanitize(name);
    await update(ref(db, "rooms/" + s + "/players/" + n), { answer: ans, submitted: true });
    // advance if all submitted
    const rRef = ref(db, "rooms/" + s);
    const snap = await get(rRef); if(!snap.exists()) return;
    const data = snap.val();
    const all = Object.values(data.players || {}).every(p => p.submitted);
    if(all) await update(rRef, { phase: "debate", timerEnd: Date.now()+120000 });
  };

  // submit one-word clue (turn-based)
  const submitOneWord = async (word) => {
    if(!roomCode || !name) return;
    const s = sanitize(roomCode); const n = sanitize(name);
    const rRef = ref(db, "rooms/" + s);
    const snap = await get(rRef); if(!snap.exists()) return;
    const data = snap.val();
    const order = Array.isArray(data.playerOrder) && data.playerOrder.length ? data.playerOrder : Object.keys(data.players || {});
    const current = data.currentTurnIndex || 0;
    const turnName = order[current % order.length];
    if(turnName !== n) return alert("Not your turn");
    const newClues = { ...(data.oneWordClues || {}) };
    newClues[n] = (word||"").trim().split(/\s+/)[0] || "";
    const nextIndex = current + 1;
    const updates = { oneWordClues: newClues, currentTurnIndex: nextIndex };
    const submittedCount = Object.keys(newClues).length;
    if(submittedCount >= order.length) { updates.phase = "debate"; updates.timerEnd = Date.now()+120000; }
    await update(rRef, updates);
  };

  // toggle vote locally (UI only)
  const toggleVoteLocal = (target) => {
    setSelectedVotes(prev => prev.includes(target) ? prev.filter(x=>x!==target) : [...prev, target]);
  };

  // submit vote (one-time)
  const submitVote = async () => {
    if(!roomCode || !name) return;
    const s = sanitize(roomCode); const n = sanitize(name);
    // prevent re-vote
    if(players[n]?.voteSubmitted) return alert("Already voted");
    await update(ref(db, "rooms/" + s + "/players/" + n), { vote: selectedVotes, voteSubmitted: true });
    // check all voted -> reveal
    const rRef = ref(db, "rooms/" + s);
    const snap = await get(rRef); if(!snap.exists()) return;
    const data = snap.val(); const all = Object.values(data.players || {}).every(p => p.voteSubmitted);
    if(all) await update(rRef, { phase: "reveal", timerEnd: null });
  };

  // reveal handlers: compute scores then show confetti for correct guesses
  useEffect(()=>{
    if(phase !== "reveal") return;
    // compute scores
    computeAndApplyScores(roomCode).catch(()=>{});
    // confetti for correct guesses
    if(confetti){
      Object.entries(players).forEach(([p,d])=>{
        const v = d.vote || [];
        const hit = v.some(x => (Array.isArray(players.impostors) && players.impostors.includes(x)) || x===NO_IMPOSTOR);
        if(hit) confetti({ particleCount: 40, spread: 70, origin: { y: 0.6 } });
      });
    }
  }, [phase]); // eslint-disable-line

  // next round (host only)
  const nextRound = async ()=>{
    if(name !== creator) return alert("Only host");
    const s = sanitize(roomCode); const rRef = ref(db, "rooms/"+s);
    const snap = await get(rRef); if(!snap.exists()) return;
    const data = snap.val() || {};
    await update(rRef, { round: (data.round||1)+1, phase: "lobby", currentPrompt:null, currentItem:null, timerEnd:null, playerOrder: [], currentTurnIndex: 0, oneWordClues: {} });
  };

  // end game (reset)
  const endGame = async ()=>{
    if(name !== creator) return alert("Only host");
    const s = sanitize(roomCode); const rRef = ref(db, "rooms/"+s);
    const snap = await get(rRef); if(!snap.exists()) return;
    const data = snap.val() || {};
    await update(rRef, { phase: "lobby", round: 1, currentPrompt:null, currentItem:null, timerEnd:null, playerOrder: [], currentTurnIndex: 0 });
  };

  // helpers for displaying votes nicely
  const voteLabel = (v) => v===NO_IMPOSTOR ? "🚫 No Impostor" : v;

  // UI rendering
  return (
    <div style={{ padding:20, fontFamily:"Orbitron, monospace", background:"#000814", minHeight:"100vh", color:"#0ff" }}>
      <header style={{ display:"flex", justifyContent:"space-between", alignItems:"center" }}>
        <div style={{ fontSize:24, fontWeight:700 }} className="neon">⚡ GUESS THE LIAR — TRON ⚡</div>
        <div>
          <strong>Room:</strong> {roomCode || "—"} &nbsp; <strong>You:</strong> {name || "anon"}
        </div>
      </header>

      <div style={{ display:"grid", gridTemplateColumns:"1fr 360px", gap:20, marginTop:16 }}>
        <div>
          {phase==="lobby" && (
            <div className="tron-panel">
              <h3>Lobby</h3>
              <div style={{ marginBottom:8 }}>
                <input placeholder="Name" value={name} onChange={e=>setName(e.target.value)} style={{ padding:8, marginRight:8 }} />
                <input placeholder="Room" value={roomCode} onChange={e=>setRoomCode(e.target.value)} style={{ padding:8, marginRight:8 }} />
                <button className="tron-btn" onClick={createRoom}>Create</button>
                <button className="tron-btn" onClick={joinRoom}>Join</button>
              </div>
              <div style={{ marginTop:8 }}>
                <div><strong>Players:</strong></div>
                <div>
                  {Object.entries(players).map(([p,d])=>(
                    <div key={p} style={{ display:"flex", alignItems:"center", gap:8, padding:6, borderBottom:"1px solid rgba(0,255,255,0.04)" }}>
                      <div className="avatar">{d.avatar||"🙂"}</div>
                      <div>{p} {p===creator ? "(host)" : ""} — {d.score||0} pts</div>
                    </div>
                  ))}
                </div>
                {creator===name && (
                  <div style={{ marginTop:10 }}>
                    <button className="tron-btn" onClick={()=>startLiarRound()}>Start Liar Round</button>
                    <button className="tron-btn" onClick={()=>startOneWordRound()}>Start One-Word Round</button>
                  </div>
                )}
              </div>
            </div>
          )}

          {phase==="answer" && mode==="liar" && (
            <div className="tron-panel">
              <h3>Answer Phase</h3>
              <div><strong>Real question:</strong> {currentPrompt}</div>
              <div style={{ marginTop:8 }}>
                <input placeholder="Type your answer" defaultValue={players[sanitize(name)]?.answer || ""} id="liarAnswer" style={{ padding:8, width:"80%" }} />
                <button className="tron-btn" onClick={()=>{ const v = document.getElementById("liarAnswer").value; submitAnswer(v); }}>Submit</button>
              </div>
              <div style={{ marginTop:8 }}>Time left: {timeLeft}s</div>
            </div>
          )}

          {phase==="debate" && mode==="liar" && (
            <div className="tron-panel">
              <h3>Debate — discuss and vote</h3>
              <div style={{ marginBottom:8 }}>
                <strong>Real question:</strong> {currentPrompt}
              </div>
              <div style={{ marginBottom:8 }}>
                {Object.keys(players).map(p=>(
                  <button key={p} className="tron-btn" onClick={()=>toggleVoteLocal(p)} style={{ margin:4, border: selectedVotes.includes(p) ? "2px solid #0f0" : "1px solid rgba(0,255,255,0.2)" }}>{p} {selectedVotes.includes(p) ? "✓" : ""}</button>
                ))}
                <button className="tron-btn" onClick={()=>toggleVoteLocal(NO_IMPOSTOR)} style={{ margin:4, border: selectedVotes.includes(NO_IMPOSTOR) ? "2px solid #ff0" : "1px solid rgba(0,255,255,0.2)" }}>🚫 No Impostor {selectedVotes.includes(NO_IMPOSTOR) ? "✓" : ""}</button>
              </div>
              <div>
                <button className="tron-btn" onClick={submitVote}>Submit Vote</button>
                <div style={{ marginTop:8 }}>Time left: {timeLeft}s</div>
              </div>
            </div>
          )}

          {phase==="reveal" && (
            <div className="tron-panel">
              <h3>Reveal</h3>
              <div><strong>Impostors:</strong> {(Array.isArray(players.impostors) ? players.impostors.join(", ") : (Array.isArray(players.impostors) ? players.impostors.join(", ") : (players.impostors || []).join(", "))) || "None"}</div>
              <h4>Votes</h4>
              <ul>
                {Object.entries(players).map(([p,data])=>(
                  <li key={p}>{p} voted for {(data.vote || []).map(v=>voteLabel(v)).join(", ") || "Nobody"}</li>
                ))}
              </ul>
              <div style={{ marginTop:8 }}>
                <button className="tron-btn" onClick={nextRound}>Next Round</button>
                <button className="tron-btn" onClick={endGame}>End Game</button>
              </div>
            </div>
          )}

          {/* One-word mode UI */}
          {phase==="oneword_round" && mode==="oneword" && (
            <div className="tron-panel">
              <h3>One-Word Round — Item: {currentItem}</h3>
              <div>Time left: {timeLeft}s</div>
              <div style={{ marginTop:8 }}>
                <div>It's <strong>{(playerOrder && playerOrder.length) ? playerOrder[turnIndex % playerOrder.length] : "—"}</strong>'s turn.</div>
                {(playerOrder && playerOrder.length && playerOrder[turnIndex % playerOrder.length] === sanitize(name)) ? (
                  <div style={{ marginTop:8 }}>
                    <input type="text" id="onewordInput" placeholder="One word..." style={{ padding:8 }} maxLength={14} />
                    <button className="tron-btn" onClick={()=>{ const w = document.getElementById("onewordInput").value; submitOneWord(w); document.getElementById("onewordInput").value=""; }}>Submit Clue</button>
                  </div>
                ) : (
                  <div style={{ marginTop:8, opacity:0.85 }}>Waiting for <strong>{(playerOrder && playerOrder.length) ? playerOrder[turnIndex % playerOrder.length] : "—"}</strong> to submit their clue...</div>
                )}
              </div>

              <div style={{ marginTop:12 }}>
                <h4>Clues so far:</h4>
                <ul>
                  {Object.entries(oneWordClues || {}).map(([p,c])=>(<li key={p}><strong>{p}:</strong> {c}</li>))}
                </ul>
              </div>
            </div>
          )}

          {phase==="oneword_vote" && mode==="oneword" && (
            <div className="tron-panel">
              <h3>One-Word — Vote for the impostor (or No Impostor)</h3>
              <div>
                {Object.keys(players).map(p=>(
                  <button key={p} className="tron-btn" onClick={()=>toggleVoteLocal(p)} style={{ margin:4, border: selectedVotes.includes(p) ? "2px solid #0f0" : "1px solid rgba(0,255,255,0.2)" }}>{p} {selectedVotes.includes(p) ? "✓" : ""}</button>
                ))}
                <button className="tron-btn" onClick={()=>toggleVoteLocal(NO_IMPOSTOR)} style={{ margin:4, border: selectedVotes.includes(NO_IMPOSTOR) ? "2px solid #ff0" : "1px solid rgba(0,255,255,0.2)" }}>🚫 No Impostor {selectedVotes.includes(NO_IMPOSTOR) ? "✓" : ""}</button>
              </div>
              <div style={{ marginTop:8 }}>
                <button className="tron-btn" onClick={submitVote}>Submit Vote</button>
                <div style={{ marginTop:8 }}>Time left: {timeLeft}s</div>
              </div>
            </div>
          )}
        </div>

        <aside style={{ width:360 }}>
          <div className="tron-panel">
            <h3>HUD</h3>
            <div>Mode: {mode}</div>
            <div>Round: {round}</div>
            <div>Players: {Object.keys(players).length}</div>
            <div>Time left: {timeLeft}s</div>
          </div>

          <div className="tron-panel">
            <h3>Scores</h3>
            <ul>
              {Object.entries(players).map(([p,d])=>(<li key={p}>{d.avatar} {p}: {d.score||0} pts</li>))}
            </ul>
          </div>

          <div className="tron-panel">
            <h3>Controls</h3>
            <div style={{ display:"flex", gap:8 }}>
              <button className="tron-btn" onClick={nextRound}>Next Round</button>
              <button className="tron-btn" onClick={endGame}>End Game</button>
            </div>
          </div>

          <div className="tron-panel">
            <h3>Options</h3>
            <div>
              <label style={{ display:"block" }}><input type="checkbox" onChange={e=>{ window.__SOUND_ENABLED__ = e.target.checked; setTimeout(()=>playSound("click"),50); }} /> Enable sounds</label>
            </div>
            <div style={{ marginTop:8 }}>
              <button className="tron-btn" onClick={()=>{ navigator.clipboard && roomCode && navigator.clipboard.writeText(roomCode); }}>Copy Room Code</button>
            </div>
          </div>
        </aside>
      </div>
    </div>
  );
}
